# ruff: noqa: E501
"""sprint3_teaching_execution

Revision ID: 0699df8f1196
Revises: c11690806d04
Create Date: 2026-09-23 00:06:30.584376
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0699df8f1196"
down_revision: str | None = "c11690806d04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teacher_profiles",
        sa.Column("teacher_no", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("phone_ciphertext", sa.Text(), nullable=True),
        sa.Column("teacher_status", sa.String(length=20), nullable=False),
        sa.Column("employment_type", sa.String(length=20), nullable=True),
        sa.Column("default_rate_amount_cent", sa.Integer(), nullable=True),
        sa.Column("default_rate_unit_minutes", sa.Integer(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("teacher_no"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "class_sessions",
        sa.Column("class_cycle_id", sa.String(length=36), nullable=False),
        sa.Column("session_no", sa.String(length=40), nullable=False),
        sa.Column("session_title", sa.String(length=200), nullable=False),
        sa.Column("session_type", sa.String(length=20), nullable=False),
        sa.Column("source_session_id", sa.String(length=36), nullable=True),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("planned_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("planned_end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("planned_minutes", sa.Integer(), nullable=False),
        sa.Column("actual_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_minutes", sa.Integer(), nullable=True),
        sa.Column("actual_adjustment_reason", sa.Text(), nullable=True),
        sa.Column("delivery_mode", sa.String(length=20), nullable=False),
        sa.Column("location_name", sa.String(length=200), nullable=True),
        sa.Column("online_meeting_url", sa.String(length=1000), nullable=True),
        sa.Column("teaching_topic", sa.String(length=500), nullable=True),
        sa.Column("teaching_content", sa.Text(), nullable=True),
        sa.Column("session_status", sa.String(length=20), nullable=False),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_cycle_id"],
            ["class_cycles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["completed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_session_id"],
            ["class_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("class_cycle_id", "session_no"),
    )
    with op.batch_alter_table("class_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_class_sessions_class_cycle_id"), ["class_cycle_id"], unique=False
        )
        batch_op.create_index(
            "ix_class_sessions_cycle_start", ["class_cycle_id", "planned_start_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_class_sessions_service_date"), ["service_date"], unique=False
        )

    op.create_table(
        "attendance_finalizations",
        sa.Column("class_session_id", sa.String(length=36), nullable=False),
        sa.Column("finalization_no", sa.Integer(), nullable=False),
        sa.Column("locked_record_count", sa.Integer(), nullable=False),
        sa.Column("total_expected_minutes", sa.Integer(), nullable=False),
        sa.Column("total_actual_minutes", sa.Integer(), nullable=False),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finalized_by", sa.String(length=36), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_session_id"],
            ["class_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["finalized_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("class_session_id", "finalization_no"),
    )
    with op.batch_alter_table("attendance_finalizations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attendance_finalizations_class_session_id"),
            ["class_session_id"],
            unique=False,
        )

    op.create_table(
        "attendance_records",
        sa.Column("class_session_id", sa.String(length=36), nullable=False),
        sa.Column("class_membership_id", sa.String(length=36), nullable=False),
        sa.Column("attendance_status", sa.String(length=20), nullable=False),
        sa.Column("expected_minutes", sa.Integer(), nullable=False),
        sa.Column("actual_attendance_minutes", sa.Integer(), nullable=False),
        sa.Column("late_minutes", sa.Integer(), nullable=False),
        sa.Column("early_leave_minutes", sa.Integer(), nullable=False),
        sa.Column("check_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("check_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workflow_status", sa.String(length=20), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("current_revision_no", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_by", sa.String(length=36), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_by", sa.String(length=36), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_membership_id"],
            ["class_memberships.id"],
        ),
        sa.ForeignKeyConstraint(
            ["class_session_id"],
            ["class_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["locked_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("class_session_id", "class_membership_id"),
    )
    with op.batch_alter_table("attendance_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attendance_records_class_membership_id"),
            ["class_membership_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_attendance_records_class_session_id"), ["class_session_id"], unique=False
        )

    op.create_table(
        "enrollment_rollover_requests",
        sa.Column("course_enrollment_id", sa.String(length=36), nullable=False),
        sa.Column("source_membership_id", sa.String(length=36), nullable=False),
        sa.Column("target_class_cycle_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("result_membership_id", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_enrollment_id"],
            ["course_enrollments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["result_membership_id"],
            ["class_memberships.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_membership_id"],
            ["class_memberships.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_class_cycle_id"],
            ["class_cycles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    with op.batch_alter_table("enrollment_rollover_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_enrollment_rollover_requests_course_enrollment_id"),
            ["course_enrollment_id"],
            unique=False,
        )

    op.create_table(
        "session_recordings",
        sa.Column("class_session_id", sa.String(length=36), nullable=False),
        sa.Column("recording_title", sa.String(length=200), nullable=False),
        sa.Column("platform_code", sa.String(length=50), nullable=False),
        sa.Column("external_url", sa.String(length=1000), nullable=False),
        sa.Column("access_code_ciphertext", sa.Text(), nullable=True),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recording_status", sa.String(length=20), nullable=False),
        sa.Column("review_status", sa.String(length=20), nullable=False),
        sa.Column("review_comment", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_session_id"],
            ["class_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("session_recordings", schema=None) as batch_op:
        batch_op.create_index(
            "ix_recordings_session_status", ["class_session_id", "recording_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_session_recordings_class_session_id"), ["class_session_id"], unique=False
        )

    op.create_table(
        "session_teacher_assignments",
        sa.Column("class_session_id", sa.String(length=36), nullable=False),
        sa.Column("teacher_id", sa.String(length=36), nullable=False),
        sa.Column("teaching_role", sa.String(length=20), nullable=False),
        sa.Column("planned_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("planned_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("planned_minutes", sa.Integer(), nullable=False),
        sa.Column("actual_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_minutes", sa.Integer(), nullable=True),
        sa.Column("settleable_minutes", sa.Integer(), nullable=True),
        sa.Column("rate_amount_cent", sa.Integer(), nullable=True),
        sa.Column("rate_unit_minutes", sa.Integer(), nullable=True),
        sa.Column("confirmation_status", sa.String(length=20), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_by", sa.String(length=36), nullable=True),
        sa.Column("adjustment_reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_session_id"],
            ["class_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teacher_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("class_session_id", "teacher_id", "teaching_role"),
    )
    with op.batch_alter_table("session_teacher_assignments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_assignment_teacher_status", ["teacher_id", "confirmation_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_session_teacher_assignments_class_session_id"),
            ["class_session_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_session_teacher_assignments_teacher_id"), ["teacher_id"], unique=False
        )

    op.create_table(
        "attendance_revisions",
        sa.Column("attendance_record_id", sa.String(length=36), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("previous_values_json", sa.Text(), nullable=False),
        sa.Column("new_values_json", sa.Text(), nullable=False),
        sa.Column("change_type", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attendance_record_id"],
            ["attendance_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attendance_record_id", "revision_no"),
    )
    with op.batch_alter_table("attendance_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attendance_revisions_attendance_record_id"),
            ["attendance_record_id"],
            unique=False,
        )

    op.create_table(
        "attendance_evidences",
        sa.Column("attendance_record_id", sa.String(length=36), nullable=False),
        sa.Column("attendance_revision_id", sa.String(length=36), nullable=True),
        sa.Column("file_object_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_type", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=36), nullable=True),
        sa.Column("delete_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attendance_record_id"],
            ["attendance_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["attendance_revision_id"],
            ["attendance_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_object_id"],
            ["file_objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attendance_evidences", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attendance_evidences_attendance_record_id"),
            ["attendance_record_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_attendance_evidences_file_object_id"), ["file_object_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance_evidences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attendance_evidences_file_object_id"))
        batch_op.drop_index(batch_op.f("ix_attendance_evidences_attendance_record_id"))

    op.drop_table("attendance_evidences")
    with op.batch_alter_table("attendance_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attendance_revisions_attendance_record_id"))

    op.drop_table("attendance_revisions")
    with op.batch_alter_table("session_teacher_assignments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_teacher_assignments_teacher_id"))
        batch_op.drop_index(batch_op.f("ix_session_teacher_assignments_class_session_id"))
        batch_op.drop_index("ix_assignment_teacher_status")

    op.drop_table("session_teacher_assignments")
    with op.batch_alter_table("session_recordings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_recordings_class_session_id"))
        batch_op.drop_index("ix_recordings_session_status")

    op.drop_table("session_recordings")
    with op.batch_alter_table("enrollment_rollover_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_enrollment_rollover_requests_course_enrollment_id"))

    op.drop_table("enrollment_rollover_requests")
    with op.batch_alter_table("attendance_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attendance_records_class_session_id"))
        batch_op.drop_index(batch_op.f("ix_attendance_records_class_membership_id"))

    op.drop_table("attendance_records")
    with op.batch_alter_table("attendance_finalizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attendance_finalizations_class_session_id"))

    op.drop_table("attendance_finalizations")
    with op.batch_alter_table("class_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_class_sessions_service_date"))
        batch_op.drop_index("ix_class_sessions_cycle_start")
        batch_op.drop_index(batch_op.f("ix_class_sessions_class_cycle_id"))

    op.drop_table("class_sessions")
    op.drop_table("teacher_profiles")
    # ### end Alembic commands ###
