# ruff: noqa: E501, I001, UP007, UP035
# fmt: off
"""add training entitlement

Revision ID: 12026a69e619
Revises: 149098fc963e
Create Date: 2026-09-23 11:05:10.344107
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '12026a69e619'
down_revision: Union[str, None] = '149098fc963e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_entitlements',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('course_enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('purchased_minutes', sa.Integer(), nullable=False),
    sa.Column('gifted_minutes', sa.Integer(), nullable=False),
    sa.Column('free_rollover_minutes', sa.Integer(), nullable=False),
    sa.Column('supplement_minutes', sa.Integer(), nullable=False),
    sa.Column('consumed_minutes', sa.Integer(), nullable=False),
    sa.Column('refund_deducted_minutes', sa.Integer(), nullable=False),
    sa.Column('entitlement_status', sa.String(length=30), nullable=False),
    sa.Column('rule_version', sa.String(length=40), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('consumed_minutes >= 0', name='ck_entitlement_consumed_nonnegative'),
    sa.CheckConstraint('free_rollover_minutes >= 0', name='ck_entitlement_free_rollover_nonnegative'),
    sa.CheckConstraint('gifted_minutes >= 0', name='ck_entitlement_gifted_nonnegative'),
    sa.CheckConstraint('purchased_minutes >= 0', name='ck_entitlement_purchased_nonnegative'),
    sa.CheckConstraint('refund_deducted_minutes >= 0', name='ck_entitlement_refund_deducted_nonnegative'),
    sa.CheckConstraint('supplement_minutes >= 0', name='ck_entitlement_supplement_nonnegative'),
    sa.ForeignKeyConstraint(['course_enrollment_id'], ['course_enrollments.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'course_enrollment_id')
    )
    with op.batch_alter_table('training_entitlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_entitlements_course_enrollment_id'), ['course_enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_entitlements_entitlement_status'), ['entitlement_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_entitlements_organization_id'), ['organization_id'], unique=False)

    op.create_table('training_entitlement_entries',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('entitlement_id', sa.String(length=36), nullable=False),
    sa.Column('entry_type', sa.String(length=40), nullable=False),
    sa.Column('minutes_delta', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('rule_version', sa.String(length=40), nullable=True),
    sa.Column('accounting_date', sa.Date(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('reversal_of_entry_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('minutes_delta <> 0', name='ck_entitlement_entry_nonzero'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entitlement_id'], ['training_entitlements.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_entry_id'], ['training_entitlement_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key')
    )
    with op.batch_alter_table('training_entitlement_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_entitlement_entries_entitlement_id'), ['entitlement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_entitlement_entries_entry_type'), ['entry_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_entitlement_entries_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_entitlement_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_entitlement_entries_organization_id'))
        batch_op.drop_index(batch_op.f('ix_training_entitlement_entries_entry_type'))
        batch_op.drop_index(batch_op.f('ix_training_entitlement_entries_entitlement_id'))

    op.drop_table('training_entitlement_entries')
    with op.batch_alter_table('training_entitlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_entitlements_organization_id'))
        batch_op.drop_index(batch_op.f('ix_training_entitlements_entitlement_status'))
        batch_op.drop_index(batch_op.f('ix_training_entitlements_course_enrollment_id'))

    op.drop_table('training_entitlements')
    # ### end Alembic commands ###
