# ruff: noqa: E501, I001, UP007, UP035
# fmt: off
"""sprint5 finance refunds teacher settlement

Revision ID: 149098fc963e
Revises: 8605eb546b45
Create Date: 2026-09-23 09:23:44.133770
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '149098fc963e'
down_revision: Union[str, None] = '8605eb546b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency_disbursements',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('disbursement_no', sa.String(length=40), nullable=False),
    sa.Column('payee_name', sa.String(length=200), nullable=False),
    sa.Column('paid_amount_cent', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_transaction_no_ciphertext', sa.Text(), nullable=True),
    sa.Column('disbursement_status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('paid_amount_cent > 0', name='ck_agency_disbursement_positive'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disbursement_no'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('agency_disbursements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agency_disbursements_disbursement_status'), ['disbursement_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agency_disbursements_organization_id'), ['organization_id'], unique=False)

    op.create_table('teacher_settlement_batches',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('batch_no', sa.String(length=40), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('settlement_status', sa.String(length=30), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('total_amount_cent', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calculated_by', sa.String(length=36), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['calculated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_no')
    )
    with op.batch_alter_table('teacher_settlement_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_settlement_batches_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_settlement_batches_settlement_status'), ['settlement_status'], unique=False)

    op.create_table('finance_attachments',
    sa.Column('owner_type', sa.String(length=40), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('file_object_id', sa.String(length=36), nullable=False),
    sa.Column('attachment_type', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_object_id'], ['file_objects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_type', 'owner_id', 'file_object_id')
    )
    with op.batch_alter_table('finance_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_attachments_file_object_id'), ['file_object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_attachments_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_attachments_owner_type'), ['owner_type'], unique=False)

    op.create_table('payments',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('payment_no', sa.String(length=40), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('payer_name', sa.String(length=120), nullable=True),
    sa.Column('received_amount_cent', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_transaction_no_ciphertext', sa.Text(), nullable=True),
    sa.Column('external_transaction_no_last4', sa.String(length=4), nullable=True),
    sa.Column('internal_receipt_no', sa.String(length=80), nullable=True),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('reversal_of_payment_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('received_amount_cent > 0', name='ck_payment_amount_positive'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('internal_receipt_no'),
    sa.UniqueConstraint('payment_no')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_student_id'), ['student_id'], unique=False)

    op.create_table('teacher_payments',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_payment_no', sa.String(length=40), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('paid_amount_cent', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_transaction_no_ciphertext', sa.Text(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('reversal_of_teacher_payment_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('paid_amount_cent > 0', name='ck_teacher_payment_positive'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_teacher_payment_id'], ['teacher_payments.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('teacher_payment_no')
    )
    with op.batch_alter_table('teacher_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_payments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_payments_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_payments_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('receivables',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('receivable_no', sa.String(length=40), nullable=False),
    sa.Column('course_enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('receivable_type', sa.String(length=30), nullable=False),
    sa.Column('economic_nature', sa.String(length=30), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('fee_policy_version_id', sa.String(length=36), nullable=True),
    sa.Column('original_amount_cent', sa.Integer(), nullable=False),
    sa.Column('adjusted_amount_cent', sa.Integer(), nullable=False),
    sa.Column('payable_amount_cent', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receivable_status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('original_amount_cent >= 0', name='ck_receivable_original_nonnegative'),
    sa.CheckConstraint('payable_amount_cent >= 0', name='ck_receivable_payable_nonnegative'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['course_enrollment_id'], ['course_enrollments.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fee_policy_version_id'], ['fee_policy_versions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receivable_no'),
    sa.UniqueConstraint('source_type', 'source_id')
    )
    with op.batch_alter_table('receivables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receivables_course_enrollment_id'), ['course_enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receivables_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receivables_receivable_status'), ['receivable_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_receivables_receivable_type'), ['receivable_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_receivables_student_id'), ['student_id'], unique=False)

    op.create_table('refund_requests',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('refund_request_no', sa.String(length=40), nullable=False),
    sa.Column('course_enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('refund_policy_version_id', sa.String(length=36), nullable=False),
    sa.Column('refund_reason', sa.Text(), nullable=False),
    sa.Column('request_status', sa.String(length=30), nullable=False),
    sa.Column('requested_amount_cent', sa.Integer(), nullable=True),
    sa.Column('calculated_refundable_amount_cent', sa.Integer(), nullable=True),
    sa.Column('approved_refund_amount_cent', sa.Integer(), nullable=True),
    sa.Column('manual_adjustment_amount_cent', sa.Integer(), nullable=False),
    sa.Column('manual_adjustment_reason', sa.Text(), nullable=True),
    sa.Column('active_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calculated_by', sa.String(length=36), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.String(length=36), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['calculated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['course_enrollment_id'], ['course_enrollments.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['refund_policy_version_id'], ['refund_policy_versions.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refund_request_no')
    )
    with op.batch_alter_table('refund_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refund_requests_course_enrollment_id'), ['course_enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refund_requests_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refund_requests_request_status'), ['request_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_refund_requests_student_id'), ['student_id'], unique=False)

    op.create_table('payment_allocations',
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('receivable_id', sa.String(length=36), nullable=False),
    sa.Column('allocated_amount_cent', sa.Integer(), nullable=False),
    sa.Column('allocation_status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('allocated_by', sa.String(length=36), nullable=False),
    sa.Column('reversal_of_allocation_id', sa.String(length=36), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('allocated_amount_cent > 0', name='ck_payment_allocation_positive'),
    sa.ForeignKeyConstraint(['allocated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['receivable_id'], ['receivables.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_allocation_id'], ['payment_allocations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_allocations_allocation_status'), ['allocation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_receivable_id'), ['receivable_id'], unique=False)

    op.create_table('receivable_adjustments',
    sa.Column('receivable_id', sa.String(length=36), nullable=False),
    sa.Column('adjustment_type', sa.String(length=20), nullable=False),
    sa.Column('amount_cent', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('reversal_of_adjustment_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_cent > 0', name='ck_receivable_adjustment_positive'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['receivable_id'], ['receivables.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_adjustment_id'], ['receivable_adjustments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receivable_adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receivable_adjustments_receivable_id'), ['receivable_id'], unique=False)

    op.create_table('refund_calculation_snapshots',
    sa.Column('refund_request_id', sa.String(length=36), nullable=False),
    sa.Column('calculation_version_no', sa.Integer(), nullable=False),
    sa.Column('tuition_receivable_id', sa.String(length=36), nullable=False),
    sa.Column('tuition_paid_allocated_cent', sa.Integer(), nullable=False),
    sa.Column('curriculum_total_minutes', sa.Integer(), nullable=False),
    sa.Column('locked_attended_minutes', sa.Integer(), nullable=False),
    sa.Column('minutes_cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('policy_method', sa.String(length=50), nullable=False),
    sa.Column('rounding_mode', sa.String(length=20), nullable=False),
    sa.Column('consumed_amount_numerator', sa.Integer(), nullable=False),
    sa.Column('consumed_amount_denominator', sa.Integer(), nullable=False),
    sa.Column('consumed_amount_cent', sa.Integer(), nullable=False),
    sa.Column('administrative_fee_cent', sa.Integer(), nullable=False),
    sa.Column('nonrefundable_fee_cent', sa.Integer(), nullable=False),
    sa.Column('previous_refunded_amount_cent', sa.Integer(), nullable=False),
    sa.Column('refundable_amount_cent', sa.Integer(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('warning_json', sa.Text(), nullable=False),
    sa.Column('calculated_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calculated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['refund_request_id'], ['refund_requests.id'], ),
    sa.ForeignKeyConstraint(['tuition_receivable_id'], ['receivables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refund_request_id', 'calculation_version_no')
    )
    with op.batch_alter_table('refund_calculation_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refund_calculation_snapshots_refund_request_id'), ['refund_request_id'], unique=False)

    op.create_table('refund_payments',
    sa.Column('refund_payment_no', sa.String(length=40), nullable=False),
    sa.Column('refund_request_id', sa.String(length=36), nullable=False),
    sa.Column('paid_amount_cent', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payee_name', sa.String(length=120), nullable=True),
    sa.Column('external_transaction_no_ciphertext', sa.Text(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('reversal_of_refund_payment_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('paid_amount_cent > 0', name='ck_refund_payment_positive'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['refund_request_id'], ['refund_requests.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_refund_payment_id'], ['refund_payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('refund_payment_no')
    )
    with op.batch_alter_table('refund_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refund_payments_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_refund_payments_refund_request_id'), ['refund_request_id'], unique=False)

    op.create_table('refund_allocations',
    sa.Column('refund_payment_id', sa.String(length=36), nullable=False),
    sa.Column('payment_allocation_id', sa.String(length=36), nullable=False),
    sa.Column('receivable_id', sa.String(length=36), nullable=False),
    sa.Column('refunded_amount_cent', sa.Integer(), nullable=False),
    sa.Column('allocation_status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('refunded_amount_cent > 0', name='ck_refund_allocation_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_allocation_id'], ['payment_allocations.id'], ),
    sa.ForeignKeyConstraint(['receivable_id'], ['receivables.id'], ),
    sa.ForeignKeyConstraint(['refund_payment_id'], ['refund_payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refund_payment_id', 'payment_allocation_id')
    )
    with op.batch_alter_table('refund_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refund_allocations_payment_allocation_id'), ['payment_allocation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refund_allocations_receivable_id'), ['receivable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refund_allocations_refund_payment_id'), ['refund_payment_id'], unique=False)

    op.create_table('refund_attendance_snapshot_lines',
    sa.Column('refund_calculation_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('attendance_record_id', sa.String(length=36), nullable=False),
    sa.Column('attendance_revision_no', sa.Integer(), nullable=False),
    sa.Column('class_session_id', sa.String(length=36), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('actual_attendance_minutes', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ),
    sa.ForeignKeyConstraint(['refund_calculation_snapshot_id'], ['refund_calculation_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refund_calculation_snapshot_id', 'attendance_record_id')
    )
    with op.batch_alter_table('refund_attendance_snapshot_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refund_attendance_snapshot_lines_refund_calculation_snapshot_id'), ['refund_calculation_snapshot_id'], unique=False)

    op.create_table('teacher_settlement_lines',
    sa.Column('settlement_batch_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('session_teacher_assignment_id', sa.String(length=36), nullable=False),
    sa.Column('class_session_id', sa.String(length=36), nullable=False),
    sa.Column('class_cycle_id', sa.String(length=36), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('teaching_role', sa.String(length=20), nullable=False),
    sa.Column('settleable_minutes', sa.Integer(), nullable=False),
    sa.Column('rate_amount_cent', sa.Integer(), nullable=False),
    sa.Column('rate_unit_minutes', sa.Integer(), nullable=False),
    sa.Column('base_amount_cent', sa.Integer(), nullable=False),
    sa.Column('adjustment_amount_cent', sa.Integer(), nullable=False),
    sa.Column('final_amount_cent', sa.Integer(), nullable=False),
    sa.Column('adjustment_reason', sa.Text(), nullable=True),
    sa.Column('line_status', sa.String(length=20), nullable=False),
    sa.Column('source_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('final_amount_cent >= 0', name='ck_teacher_line_final_nonnegative'),
    sa.ForeignKeyConstraint(['class_cycle_id'], ['class_cycles.id'], ),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_teacher_assignment_id'], ['session_teacher_assignments.id'], ),
    sa.ForeignKeyConstraint(['settlement_batch_id'], ['teacher_settlement_batches.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_teacher_assignment_id')
    )
    with op.batch_alter_table('teacher_settlement_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_settlement_lines_settlement_batch_id'), ['settlement_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_settlement_lines_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('agency_payables',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('agency_payable_no', sa.String(length=40), nullable=False),
    sa.Column('payee_type', sa.String(length=30), nullable=False),
    sa.Column('payee_name', sa.String(length=200), nullable=False),
    sa.Column('exam_batch_id', sa.String(length=36), nullable=True),
    sa.Column('exam_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('source_receivable_id', sa.String(length=36), nullable=False),
    sa.Column('payable_amount_cent', sa.Integer(), nullable=False),
    sa.Column('payable_status', sa.String(length=30), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('payable_amount_cent >= 0', name='ck_agency_payable_nonnegative'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exam_attempt_id'], ['exam_attempts.id'], ),
    sa.ForeignKeyConstraint(['exam_batch_id'], ['exam_batches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_receivable_id'], ['receivables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_payable_no'),
    sa.UniqueConstraint('source_receivable_id')
    )
    with op.batch_alter_table('agency_payables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agency_payables_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agency_payables_payable_status'), ['payable_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agency_payables_source_receivable_id'), ['source_receivable_id'], unique=False)

    op.create_table('teacher_payment_allocations',
    sa.Column('teacher_payment_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_settlement_line_id', sa.String(length=36), nullable=False),
    sa.Column('allocated_amount_cent', sa.Integer(), nullable=False),
    sa.Column('allocation_status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('reversal_of_allocation_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('allocated_amount_cent > 0', name='ck_teacher_payment_allocation_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_allocation_id'], ['teacher_payment_allocations.id'], ),
    sa.ForeignKeyConstraint(['teacher_payment_id'], ['teacher_payments.id'], ),
    sa.ForeignKeyConstraint(['teacher_settlement_line_id'], ['teacher_settlement_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('teacher_payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_payment_allocations_teacher_payment_id'), ['teacher_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_payment_allocations_teacher_settlement_line_id'), ['teacher_settlement_line_id'], unique=False)

    op.create_table('agency_disbursement_allocations',
    sa.Column('agency_disbursement_id', sa.String(length=36), nullable=False),
    sa.Column('agency_payable_id', sa.String(length=36), nullable=False),
    sa.Column('allocated_amount_cent', sa.Integer(), nullable=False),
    sa.Column('allocation_status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('reversal_of_allocation_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('allocated_amount_cent > 0', name='ck_agency_allocation_positive'),
    sa.ForeignKeyConstraint(['agency_disbursement_id'], ['agency_disbursements.id'], ),
    sa.ForeignKeyConstraint(['agency_payable_id'], ['agency_payables.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_allocation_id'], ['agency_disbursement_allocations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('agency_disbursement_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agency_disbursement_allocations_agency_disbursement_id'), ['agency_disbursement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agency_disbursement_allocations_agency_payable_id'), ['agency_payable_id'], unique=False)

    with op.batch_alter_table('refund_policy_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calculation_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('consumed_minutes_basis', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rounding_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('minimum_deduction_amount_cent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('administrative_fee_amount_cent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('initial_exam_fee_refundable', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('resit_fee_refundable', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('refund_deadline_rule', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refund_policy_versions', schema=None) as batch_op:
        batch_op.drop_column('refund_deadline_rule')
        batch_op.drop_column('resit_fee_refundable')
        batch_op.drop_column('initial_exam_fee_refundable')
        batch_op.drop_column('administrative_fee_amount_cent')
        batch_op.drop_column('minimum_deduction_amount_cent')
        batch_op.drop_column('rounding_mode')
        batch_op.drop_column('consumed_minutes_basis')
        batch_op.drop_column('calculation_method')

    with op.batch_alter_table('agency_disbursement_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agency_disbursement_allocations_agency_payable_id'))
        batch_op.drop_index(batch_op.f('ix_agency_disbursement_allocations_agency_disbursement_id'))

    op.drop_table('agency_disbursement_allocations')
    with op.batch_alter_table('teacher_payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_payment_allocations_teacher_settlement_line_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_payment_allocations_teacher_payment_id'))

    op.drop_table('teacher_payment_allocations')
    with op.batch_alter_table('agency_payables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agency_payables_source_receivable_id'))
        batch_op.drop_index(batch_op.f('ix_agency_payables_payable_status'))
        batch_op.drop_index(batch_op.f('ix_agency_payables_organization_id'))

    op.drop_table('agency_payables')
    with op.batch_alter_table('teacher_settlement_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_settlement_lines_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_settlement_lines_settlement_batch_id'))

    op.drop_table('teacher_settlement_lines')
    with op.batch_alter_table('refund_attendance_snapshot_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refund_attendance_snapshot_lines_refund_calculation_snapshot_id'))

    op.drop_table('refund_attendance_snapshot_lines')
    with op.batch_alter_table('refund_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refund_allocations_refund_payment_id'))
        batch_op.drop_index(batch_op.f('ix_refund_allocations_receivable_id'))
        batch_op.drop_index(batch_op.f('ix_refund_allocations_payment_allocation_id'))

    op.drop_table('refund_allocations')
    with op.batch_alter_table('refund_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refund_payments_refund_request_id'))
        batch_op.drop_index(batch_op.f('ix_refund_payments_payment_status'))

    op.drop_table('refund_payments')
    with op.batch_alter_table('refund_calculation_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refund_calculation_snapshots_refund_request_id'))

    op.drop_table('refund_calculation_snapshots')
    with op.batch_alter_table('receivable_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receivable_adjustments_receivable_id'))

    op.drop_table('receivable_adjustments')
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_allocations_receivable_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_allocation_status'))

    op.drop_table('payment_allocations')
    with op.batch_alter_table('refund_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refund_requests_student_id'))
        batch_op.drop_index(batch_op.f('ix_refund_requests_request_status'))
        batch_op.drop_index(batch_op.f('ix_refund_requests_organization_id'))
        batch_op.drop_index(batch_op.f('ix_refund_requests_course_enrollment_id'))

    op.drop_table('refund_requests')
    with op.batch_alter_table('receivables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receivables_student_id'))
        batch_op.drop_index(batch_op.f('ix_receivables_receivable_type'))
        batch_op.drop_index(batch_op.f('ix_receivables_receivable_status'))
        batch_op.drop_index(batch_op.f('ix_receivables_organization_id'))
        batch_op.drop_index(batch_op.f('ix_receivables_course_enrollment_id'))

    op.drop_table('receivables')
    with op.batch_alter_table('teacher_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_payments_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_payments_payment_status'))
        batch_op.drop_index(batch_op.f('ix_teacher_payments_organization_id'))

    op.drop_table('teacher_payments')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_student_id'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_status'))
        batch_op.drop_index(batch_op.f('ix_payments_organization_id'))

    op.drop_table('payments')
    with op.batch_alter_table('finance_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_attachments_owner_type'))
        batch_op.drop_index(batch_op.f('ix_finance_attachments_owner_id'))
        batch_op.drop_index(batch_op.f('ix_finance_attachments_file_object_id'))

    op.drop_table('finance_attachments')
    with op.batch_alter_table('teacher_settlement_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_settlement_batches_settlement_status'))
        batch_op.drop_index(batch_op.f('ix_teacher_settlement_batches_organization_id'))

    op.drop_table('teacher_settlement_batches')
    with op.batch_alter_table('agency_disbursements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agency_disbursements_organization_id'))
        batch_op.drop_index(batch_op.f('ix_agency_disbursements_disbursement_status'))

    op.drop_table('agency_disbursements')
    # ### end Alembic commands ###
