# ruff: noqa: E501
"""sprint4_exam_details

Revision ID: 66f961811c0b
Revises: c8ddc70c572c
Create Date: 2026-09-23 07:51:39.475146
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "66f961811c0b"
down_revision: str | None = "c8ddc70c572c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exam_batch_subjects",
        sa.Column("exam_batch_id", sa.String(length=36), nullable=False),
        sa.Column("course_subject_version_id", sa.String(length=36), nullable=False),
        sa.Column("exam_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exam_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("venue_name", sa.String(length=200), nullable=True),
        sa.Column("registration_deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("initial_exam_fee_amount_cent", sa.Integer(), nullable=True),
        sa.Column("resit_fee_amount_cent", sa.Integer(), nullable=True),
        sa.Column("subject_status", sa.String(length=20), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_subject_version_id"],
            ["course_subject_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exam_batch_id"],
            ["exam_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exam_batch_id", "course_subject_version_id"),
    )
    with op.batch_alter_table("exam_batch_subjects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exam_batch_subjects_course_subject_version_id"),
            ["course_subject_version_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_exam_batch_subjects_exam_batch_id"), ["exam_batch_id"], unique=False
        )

    op.create_table(
        "exam_registrations",
        sa.Column("registration_no", sa.String(length=40), nullable=False),
        sa.Column("course_enrollment_id", sa.String(length=36), nullable=False),
        sa.Column("exam_batch_id", sa.String(length=36), nullable=False),
        sa.Column("registration_status", sa.String(length=30), nullable=False),
        sa.Column("registration_source", sa.String(length=20), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_registration_no", sa.String(length=100), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_enrollment_id"],
            ["course_enrollments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exam_batch_id"],
            ["exam_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_enrollment_id", "exam_batch_id"),
        sa.UniqueConstraint("idempotency_key"),
        sa.UniqueConstraint("registration_no"),
    )
    with op.batch_alter_table("exam_registrations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exam_registrations_course_enrollment_id"),
            ["course_enrollment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_exam_registrations_exam_batch_id"), ["exam_batch_id"], unique=False
        )

    op.create_table(
        "certificate_delivery_events",
        sa.Column("certificate_case_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("from_status", sa.String(length=30), nullable=False),
        sa.Column("to_status", sa.String(length=30), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("operator_id", sa.String(length=36), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("evidence_file_object_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["certificate_case_id"],
            ["certificate_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evidence_file_object_id"],
            ["file_objects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("certificate_delivery_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_certificate_delivery_events_certificate_case_id"),
            ["certificate_case_id"],
            unique=False,
        )

    op.create_table(
        "exam_registration_subjects",
        sa.Column("exam_registration_id", sa.String(length=36), nullable=False),
        sa.Column("exam_batch_subject_id", sa.String(length=36), nullable=False),
        sa.Column("course_subject_version_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_type", sa.String(length=20), nullable=False),
        sa.Column("planned_attempt_no", sa.Integer(), nullable=False),
        sa.Column("subject_registration_status", sa.String(length=30), nullable=False),
        sa.Column("admission_ticket_no_ciphertext", sa.Text(), nullable=True),
        sa.Column("admission_ticket_no_last4", sa.String(length=4), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_subject_version_id"],
            ["course_subject_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exam_batch_subject_id"],
            ["exam_batch_subjects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exam_registration_id"],
            ["exam_registrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exam_registration_id", "exam_batch_subject_id"),
    )
    with op.batch_alter_table("exam_registration_subjects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exam_registration_subjects_course_subject_version_id"),
            ["course_subject_version_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_exam_registration_subjects_exam_batch_subject_id"),
            ["exam_batch_subject_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_exam_registration_subjects_exam_registration_id"),
            ["exam_registration_id"],
            unique=False,
        )

    op.create_table(
        "exam_result_revisions",
        sa.Column("exam_attempt_id", sa.String(length=36), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("previous_values_json", sa.Text(), nullable=False),
        sa.Column("new_values_json", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence_file_object_id", sa.String(length=36), nullable=True),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("revised_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_file_object_id"],
            ["file_objects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exam_attempt_id"],
            ["exam_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revised_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exam_attempt_id", "revision_no"),
    )
    with op.batch_alter_table("exam_result_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exam_result_revisions_exam_attempt_id"),
            ["exam_attempt_id"],
            unique=False,
        )

    with op.batch_alter_table("certificate_cases", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("certificate_type_code", sa.String(length=50), nullable=False)
        )
        batch_op.add_column(
            sa.Column("certificate_type_name_snapshot", sa.String(length=120), nullable=False)
        )
        batch_op.add_column(sa.Column("issuing_authority", sa.String(length=200), nullable=True))
        batch_op.add_column(
            sa.Column("application_submitted_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(
            sa.Column("school_received_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("delivery_method", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("recipient_name", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("courier_company", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("tracking_no_ciphertext", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("exception_reason", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("updated_by", sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            "fk_certificate_cases_updated_by", "users", ["updated_by"], ["id"]
        )

    with op.batch_alter_table("exam_attempts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("exam_registration_subject_id", sa.String(length=36), nullable=True)
        )
        batch_op.add_column(sa.Column("attendance_status", sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column("max_score_value_scaled", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("result_source", sa.String(length=20), nullable=False))
        batch_op.add_column(
            sa.Column("result_published_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("remarks", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("updated_by", sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint(
            "uq_exam_attempt_registration_subject", ["exam_registration_subject_id"]
        )
        batch_op.create_foreign_key(
            "fk_exam_attempt_registration_subject",
            "exam_registration_subjects",
            ["exam_registration_subject_id"],
            ["id"],
        )
        batch_op.create_foreign_key("fk_exam_attempts_updated_by", "users", ["updated_by"], ["id"])

    with op.batch_alter_table("exam_batches", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("organizing_institution", sa.String(length=200), nullable=True)
        )
        batch_op.add_column(
            sa.Column("registration_open_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("registration_deadline_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("cancellation_reason", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("remarks", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("updated_by", sa.String(length=36), nullable=True))
        batch_op.create_foreign_key("fk_exam_batches_updated_by", "users", ["updated_by"], ["id"])

    with op.batch_alter_table("exam_fee_assessments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("exam_registration_subject_id", sa.String(length=36), nullable=True)
        )
        batch_op.add_column(
            sa.Column("course_subject_version_id", sa.String(length=36), nullable=True)
        )
        batch_op.add_column(sa.Column("fee_policy_version_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("policy_snapshot_description", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("confirmed_by", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("waiver_reason", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("cancellation_reason", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("finance_reference", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("updated_by", sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            "fk_exam_fee_subject", "course_subject_versions", ["course_subject_version_id"], ["id"]
        )
        batch_op.create_foreign_key("fk_exam_fee_updated_by", "users", ["updated_by"], ["id"])
        batch_op.create_foreign_key(
            "fk_exam_fee_registration_subject",
            "exam_registration_subjects",
            ["exam_registration_subject_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            "fk_exam_fee_policy", "fee_policy_versions", ["fee_policy_version_id"], ["id"]
        )
        batch_op.create_foreign_key("fk_exam_fee_confirmed_by", "users", ["confirmed_by"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exam_fee_assessments", schema=None) as batch_op:
        batch_op.drop_constraint("fk_exam_fee_confirmed_by", type_="foreignkey")
        batch_op.drop_constraint("fk_exam_fee_policy", type_="foreignkey")
        batch_op.drop_constraint("fk_exam_fee_registration_subject", type_="foreignkey")
        batch_op.drop_constraint("fk_exam_fee_updated_by", type_="foreignkey")
        batch_op.drop_constraint("fk_exam_fee_subject", type_="foreignkey")
        batch_op.drop_column("updated_by")
        batch_op.drop_column("finance_reference")
        batch_op.drop_column("cancellation_reason")
        batch_op.drop_column("waiver_reason")
        batch_op.drop_column("confirmed_by")
        batch_op.drop_column("confirmed_at")
        batch_op.drop_column("policy_snapshot_description")
        batch_op.drop_column("fee_policy_version_id")
        batch_op.drop_column("course_subject_version_id")
        batch_op.drop_column("exam_registration_subject_id")

    with op.batch_alter_table("exam_batches", schema=None) as batch_op:
        batch_op.drop_constraint("fk_exam_batches_updated_by", type_="foreignkey")
        batch_op.drop_column("updated_by")
        batch_op.drop_column("remarks")
        batch_op.drop_column("cancellation_reason")
        batch_op.drop_column("registration_deadline_at")
        batch_op.drop_column("registration_open_at")
        batch_op.drop_column("organizing_institution")

    with op.batch_alter_table("exam_attempts", schema=None) as batch_op:
        batch_op.drop_constraint("fk_exam_attempts_updated_by", type_="foreignkey")
        batch_op.drop_constraint("fk_exam_attempt_registration_subject", type_="foreignkey")
        batch_op.drop_constraint("uq_exam_attempt_registration_subject", type_="unique")
        batch_op.drop_column("updated_by")
        batch_op.drop_column("remarks")
        batch_op.drop_column("result_published_at")
        batch_op.drop_column("result_source")
        batch_op.drop_column("max_score_value_scaled")
        batch_op.drop_column("attendance_status")
        batch_op.drop_column("exam_registration_subject_id")

    with op.batch_alter_table("certificate_cases", schema=None) as batch_op:
        batch_op.drop_constraint("fk_certificate_cases_updated_by", type_="foreignkey")
        batch_op.drop_column("updated_by")
        batch_op.drop_column("exception_reason")
        batch_op.drop_column("tracking_no_ciphertext")
        batch_op.drop_column("courier_company")
        batch_op.drop_column("recipient_name")
        batch_op.drop_column("delivery_method")
        batch_op.drop_column("delivered_at")
        batch_op.drop_column("ready_at")
        batch_op.drop_column("school_received_at")
        batch_op.drop_column("issued_at")
        batch_op.drop_column("application_submitted_at")
        batch_op.drop_column("issuing_authority")
        batch_op.drop_column("certificate_type_name_snapshot")
        batch_op.drop_column("certificate_type_code")

    with op.batch_alter_table("exam_result_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_result_revisions_exam_attempt_id"))

    op.drop_table("exam_result_revisions")
    with op.batch_alter_table("exam_registration_subjects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_registration_subjects_exam_registration_id"))
        batch_op.drop_index(batch_op.f("ix_exam_registration_subjects_exam_batch_subject_id"))
        batch_op.drop_index(batch_op.f("ix_exam_registration_subjects_course_subject_version_id"))

    op.drop_table("exam_registration_subjects")
    with op.batch_alter_table("certificate_delivery_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_certificate_delivery_events_certificate_case_id"))

    op.drop_table("certificate_delivery_events")
    with op.batch_alter_table("exam_registrations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_registrations_exam_batch_id"))
        batch_op.drop_index(batch_op.f("ix_exam_registrations_course_enrollment_id"))

    op.drop_table("exam_registrations")
    with op.batch_alter_table("exam_batch_subjects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_batch_subjects_exam_batch_id"))
        batch_op.drop_index(batch_op.f("ix_exam_batch_subjects_course_subject_version_id"))

    op.drop_table("exam_batch_subjects")
    # ### end Alembic commands ###
