# ruff: noqa: E501, I001, UP007, UP035
"""sprint1_student_course_enrollment

Revision ID: 83208c080abe
Revises: da37eb8ecd8a
Create Date: 2026-09-22 09:20:17.430083
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "83208c080abe"
down_revision: Union[str, None] = "da37eb8ecd8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "curriculum_versions",
        sa.Column("version_no", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("total_minutes", sa.Integer(), nullable=False),
        sa.Column("theory_minutes", sa.Integer(), nullable=True),
        sa.Column("practical_minutes", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_no"),
    )
    with op.batch_alter_table("curriculum_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_curriculum_versions_status"), ["status"], unique=False)

    op.create_table(
        "exam_scheme_versions",
        sa.Column("version_no", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("scheme_type", sa.String(length=50), nullable=False),
        sa.Column("pass_rule_description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_no"),
    )
    with op.batch_alter_table("exam_scheme_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exam_scheme_versions_status"), ["status"], unique=False
        )

    op.create_table(
        "fee_policy_versions",
        sa.Column("version_no", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("tuition_amount_cent", sa.Integer(), nullable=False),
        sa.Column("initial_exam_fee_cent", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_no"),
    )
    with op.batch_alter_table("fee_policy_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fee_policy_versions_status"), ["status"], unique=False)

    op.create_table(
        "refund_policy_versions",
        sa.Column("version_no", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("policy_description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_no"),
    )
    with op.batch_alter_table("refund_policy_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_refund_policy_versions_status"), ["status"], unique=False
        )

    op.create_table(
        "course_subject_versions",
        sa.Column("exam_scheme_version_id", sa.String(length=36), nullable=False),
        sa.Column("subject_code", sa.String(length=40), nullable=False),
        sa.Column("subject_name", sa.String(length=120), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("passing_score", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exam_scheme_version_id"],
            ["exam_scheme_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exam_scheme_version_id", "subject_code"),
    )
    with op.batch_alter_table("course_subject_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_course_subject_versions_exam_scheme_version_id"),
            ["exam_scheme_version_id"],
            unique=False,
        )

    op.create_table(
        "course_catalogs",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("course_code", sa.String(length=40), nullable=False),
        sa.Column("course_name", sa.String(length=120), nullable=False),
        sa.Column("category_code", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "course_code"),
    )
    with op.batch_alter_table("course_catalogs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_course_catalogs_enabled"), ["enabled"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_course_catalogs_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "student_import_batches",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirm_idempotency_key", sa.String(length=100), nullable=True),
        sa.Column("preview_payload_ciphertext", sa.Text(), nullable=False),
        sa.Column("summary_json", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("confirm_idempotency_key"),
    )
    with op.batch_alter_table("student_import_batches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_student_import_batches_created_by"), ["created_by"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_student_import_batches_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_student_import_batches_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_student_import_batches_status"), ["status"], unique=False
        )

    op.create_table(
        "students",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("student_no", sa.String(length=32), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("gender", sa.String(length=20), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("phone_ciphertext", sa.Text(), nullable=True),
        sa.Column("phone_blind_index", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("education_level", sa.String(length=50), nullable=True),
        sa.Column("residence_region_code", sa.String(length=50), nullable=True),
        sa.Column("address_ciphertext", sa.Text(), nullable=True),
        sa.Column("source_channel", sa.String(length=80), nullable=True),
        sa.Column("student_status", sa.String(length=20), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "student_no"),
    )
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.create_index(
            "ix_students_org_name", ["organization_id", "full_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_students_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_students_phone_blind_index"), ["phone_blind_index"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_students_student_status"), ["student_status"], unique=False
        )

    op.create_table(
        "course_offering_versions",
        sa.Column("course_catalog_id", sa.String(length=36), nullable=False),
        sa.Column("version_no", sa.String(length=40), nullable=False),
        sa.Column("version_name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_until", sa.Date(), nullable=True),
        sa.Column("curriculum_version_id", sa.String(length=36), nullable=True),
        sa.Column("exam_scheme_version_id", sa.String(length=36), nullable=True),
        sa.Column("fee_policy_version_id", sa.String(length=36), nullable=True),
        sa.Column("refund_policy_version_id", sa.String(length=36), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_by", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_catalog_id"],
            ["course_catalogs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["curriculum_version_id"],
            ["curriculum_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exam_scheme_version_id"],
            ["exam_scheme_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fee_policy_version_id"],
            ["fee_policy_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["refund_policy_version_id"],
            ["refund_policy_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_catalog_id", "version_no"),
    )
    with op.batch_alter_table("course_offering_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_course_offering_versions_course_catalog_id"),
            ["course_catalog_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_course_offering_versions_status"), ["status"], unique=False
        )

    op.create_table(
        "student_identity_documents",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("document_type", sa.String(length=30), nullable=False),
        sa.Column("document_number_ciphertext", sa.Text(), nullable=False),
        sa.Column("document_number_blind_index", sa.String(length=64), nullable=False),
        sa.Column("document_number_last4", sa.String(length=4), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("verification_status", sa.String(length=30), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_type", "document_number_blind_index"),
    )
    with op.batch_alter_table("student_identity_documents", schema=None) as batch_op:
        batch_op.create_index(
            "ix_student_documents_student_primary", ["student_id", "is_primary"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_student_identity_documents_student_id"), ["student_id"], unique=False
        )

    op.create_table(
        "student_import_lines",
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=True),
        sa.Column("result_json", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["student_import_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "row_number"),
    )
    with op.batch_alter_table("student_import_lines", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_student_import_lines_batch_id"), ["batch_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_student_import_lines_status"), ["status"], unique=False
        )

    op.create_table(
        "class_cycles",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("class_code", sa.String(length=40), nullable=False),
        sa.Column("class_name", sa.String(length=120), nullable=False),
        sa.Column("course_offering_version_id", sa.String(length=36), nullable=False),
        sa.Column("planned_start_date", sa.Date(), nullable=True),
        sa.Column("planned_end_date", sa.Date(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("class_status", sa.String(length=30), nullable=False),
        sa.Column("homeroom_teacher_id", sa.String(length=36), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_offering_version_id"],
            ["course_offering_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["homeroom_teacher_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "class_code"),
    )
    with op.batch_alter_table("class_cycles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_class_cycles_class_status"), ["class_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_class_cycles_course_offering_version_id"),
            ["course_offering_version_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_class_cycles_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "course_enrollments",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("enrollment_no", sa.String(length=32), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("course_offering_version_id", sa.String(length=36), nullable=False),
        sa.Column("curriculum_version_id", sa.String(length=36), nullable=False),
        sa.Column("exam_scheme_version_id", sa.String(length=36), nullable=False),
        sa.Column("fee_policy_version_id", sa.String(length=36), nullable=False),
        sa.Column("refund_policy_version_id", sa.String(length=36), nullable=False),
        sa.Column("enrolled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("enrollment_channel", sa.String(length=80), nullable=True),
        sa.Column("idempotency_key", sa.String(length=100), nullable=True),
        sa.Column("lifecycle_status", sa.String(length=30), nullable=False),
        sa.Column("learning_status", sa.String(length=30), nullable=False),
        sa.Column("exam_status", sa.String(length=30), nullable=False),
        sa.Column("financial_status", sa.String(length=30), nullable=False),
        sa.Column("certificate_status", sa.String(length=30), nullable=False),
        sa.Column("funding_status", sa.String(length=30), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by", sa.String(length=36), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cancelled_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["course_offering_version_id"],
            ["course_offering_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["curriculum_version_id"],
            ["curriculum_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exam_scheme_version_id"],
            ["exam_scheme_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fee_policy_version_id"],
            ["fee_policy_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["refund_policy_version_id"],
            ["refund_policy_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "enrollment_no"),
        sa.UniqueConstraint("organization_id", "idempotency_key"),
    )
    with op.batch_alter_table("course_enrollments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_course_enrollments_course_offering_version_id"),
            ["course_offering_version_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_course_enrollments_lifecycle_status"), ["lifecycle_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_course_enrollments_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_course_enrollments_student_id"), ["student_id"], unique=False
        )
        batch_op.create_index(
            "ix_enrollments_student_status", ["student_id", "lifecycle_status"], unique=False
        )

    op.create_table(
        "class_memberships",
        sa.Column("class_cycle_id", sa.String(length=36), nullable=False),
        sa.Column("course_enrollment_id", sa.String(length=36), nullable=False),
        sa.Column("entered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("membership_status", sa.String(length=30), nullable=False),
        sa.Column("entry_reason", sa.String(length=80), nullable=False),
        sa.Column("exit_reason", sa.Text(), nullable=True),
        sa.Column("previous_membership_id", sa.String(length=36), nullable=True),
        sa.Column("financial_treatment", sa.String(length=80), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_cycle_id"],
            ["class_cycles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["course_enrollment_id"],
            ["course_enrollments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_membership_id"],
            ["class_memberships.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("class_memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_class_memberships_class_cycle_id"), ["class_cycle_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_class_memberships_course_enrollment_id"),
            ["course_enrollment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_class_memberships_membership_status"),
            ["membership_status"],
            unique=False,
        )
        batch_op.create_index(
            "uq_class_memberships_active_enrollment",
            ["course_enrollment_id"],
            unique=True,
            sqlite_where=sa.text("membership_status = 'ACTIVE'"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("class_memberships", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_class_memberships_active_enrollment",
            sqlite_where=sa.text("membership_status = 'ACTIVE'"),
        )
        batch_op.drop_index(batch_op.f("ix_class_memberships_membership_status"))
        batch_op.drop_index(batch_op.f("ix_class_memberships_course_enrollment_id"))
        batch_op.drop_index(batch_op.f("ix_class_memberships_class_cycle_id"))

    op.drop_table("class_memberships")
    with op.batch_alter_table("course_enrollments", schema=None) as batch_op:
        batch_op.drop_index("ix_enrollments_student_status")
        batch_op.drop_index(batch_op.f("ix_course_enrollments_student_id"))
        batch_op.drop_index(batch_op.f("ix_course_enrollments_organization_id"))
        batch_op.drop_index(batch_op.f("ix_course_enrollments_lifecycle_status"))
        batch_op.drop_index(batch_op.f("ix_course_enrollments_course_offering_version_id"))

    op.drop_table("course_enrollments")
    with op.batch_alter_table("class_cycles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_class_cycles_organization_id"))
        batch_op.drop_index(batch_op.f("ix_class_cycles_course_offering_version_id"))
        batch_op.drop_index(batch_op.f("ix_class_cycles_class_status"))

    op.drop_table("class_cycles")
    with op.batch_alter_table("student_import_lines", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_student_import_lines_status"))
        batch_op.drop_index(batch_op.f("ix_student_import_lines_batch_id"))

    op.drop_table("student_import_lines")
    with op.batch_alter_table("student_identity_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_student_identity_documents_student_id"))
        batch_op.drop_index("ix_student_documents_student_primary")

    op.drop_table("student_identity_documents")
    with op.batch_alter_table("course_offering_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_course_offering_versions_status"))
        batch_op.drop_index(batch_op.f("ix_course_offering_versions_course_catalog_id"))

    op.drop_table("course_offering_versions")
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_students_student_status"))
        batch_op.drop_index(batch_op.f("ix_students_phone_blind_index"))
        batch_op.drop_index(batch_op.f("ix_students_organization_id"))
        batch_op.drop_index("ix_students_org_name")

    op.drop_table("students")
    with op.batch_alter_table("student_import_batches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_student_import_batches_status"))
        batch_op.drop_index(batch_op.f("ix_student_import_batches_organization_id"))
        batch_op.drop_index(batch_op.f("ix_student_import_batches_expires_at"))
        batch_op.drop_index(batch_op.f("ix_student_import_batches_created_by"))

    op.drop_table("student_import_batches")
    with op.batch_alter_table("course_catalogs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_course_catalogs_organization_id"))
        batch_op.drop_index(batch_op.f("ix_course_catalogs_enabled"))

    op.drop_table("course_catalogs")
    with op.batch_alter_table("course_subject_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_course_subject_versions_exam_scheme_version_id"))

    op.drop_table("course_subject_versions")
    with op.batch_alter_table("refund_policy_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refund_policy_versions_status"))

    op.drop_table("refund_policy_versions")
    with op.batch_alter_table("fee_policy_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fee_policy_versions_status"))

    op.drop_table("fee_policy_versions")
    with op.batch_alter_table("exam_scheme_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_scheme_versions_status"))

    op.drop_table("exam_scheme_versions")
    with op.batch_alter_table("curriculum_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_curriculum_versions_status"))

    op.drop_table("curriculum_versions")
    # ### end Alembic commands ###
