"""sprint2_attachments

Revision ID: c11690806d04
Revises: 83208c080abe
Create Date: 2026-09-22 23:49:24.013158
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c11690806d04"
down_revision: str | None = "83208c080abe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_categories",
        sa.Column("category_code", sa.String(length=60), nullable=False),
        sa.Column("category_name", sa.String(length=120), nullable=False),
        sa.Column("owner_domain", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sensitivity_level", sa.String(length=30), nullable=False),
        sa.Column("max_size_bytes", sa.Integer(), nullable=False),
        sa.Column("allow_multiple", sa.Boolean(), nullable=False),
        sa.Column("requires_review", sa.Boolean(), nullable=False),
        sa.Column("validity_required", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category_code"),
    )
    op.create_table(
        "file_objects",
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("safe_extension", sa.String(length=12), nullable=False),
        sa.Column("declared_content_type", sa.String(length=120), nullable=True),
        sa.Column("detected_content_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("file_status", sa.String(length=20), nullable=False),
        sa.Column("sensitivity_level", sa.String(length=30), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("deleted_by", sa.String(length=36), nullable=True),
        sa.Column("delete_reason", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("file_objects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_file_objects_sha256"), ["sha256"], unique=False)
        batch_op.create_index("ix_file_objects_status", ["file_status"], unique=False)

    op.create_table(
        "document_category_allowed_types",
        sa.Column("category_id", sa.String(length=36), nullable=False),
        sa.Column("extension", sa.String(length=12), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("detected_content_type", sa.String(length=120), nullable=False),
        sa.Column("inline_preview", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["document_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category_id", "extension", "detected_content_type"),
    )
    with op.batch_alter_table("document_category_allowed_types", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_category_allowed_types_category_id"),
            ["category_id"],
            unique=False,
        )

    op.create_table(
        "file_replicas",
        sa.Column("file_object_id", sa.String(length=36), nullable=False),
        sa.Column("storage_provider", sa.String(length=20), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("replica_status", sa.String(length=20), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("provider_etag", sa.String(length=255), nullable=True),
        sa.Column("provider_version_id", sa.String(length=255), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=80), nullable=True),
        sa.Column("failure_message_sanitized", sa.String(length=255), nullable=True),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_object_id"],
            ["file_objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_provider", "object_key"),
    )
    with op.batch_alter_table("file_replicas", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_file_replicas_file_object_id"), ["file_object_id"], unique=False
        )
        batch_op.create_index(
            "uq_file_replicas_primary",
            ["file_object_id"],
            unique=True,
            sqlite_where=sa.text("is_primary = 1 AND deleted_at IS NULL"),
        )

    op.create_table(
        "student_document_requirements",
        sa.Column("requirement_code", sa.String(length=80), nullable=False),
        sa.Column("requirement_name", sa.String(length=120), nullable=False),
        sa.Column("category_id", sa.String(length=36), nullable=False),
        sa.Column("applicable_course_catalog_id", sa.String(length=36), nullable=True),
        sa.Column("required_count", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_until", sa.Date(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["applicable_course_catalog_id"],
            ["course_catalogs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["document_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("requirement_code"),
    )
    with op.batch_alter_table("student_document_requirements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_student_document_requirements_category_id"),
            ["category_id"],
            unique=False,
        )

    op.create_table(
        "student_documents",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("file_object_id", sa.String(length=36), nullable=False),
        sa.Column("category_id", sa.String(length=36), nullable=False),
        sa.Column("document_status", sa.String(length=30), nullable=False),
        sa.Column("document_number_masked", sa.String(length=80), nullable=True),
        sa.Column("document_date", sa.Date(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("supersedes_document_id", sa.String(length=36), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("review_comment", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=36), nullable=True),
        sa.Column("delete_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["document_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_object_id"],
            ["file_objects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_document_id"],
            ["student_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("student_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_student_documents_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_student_documents_file_object_id"), ["file_object_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_student_documents_student_id"), ["student_id"], unique=False
        )
        batch_op.create_index(
            "ix_student_documents_student_status", ["student_id", "document_status"], unique=False
        )
        batch_op.create_index(
            "uq_student_documents_primary",
            ["student_id", "category_id"],
            unique=True,
            sqlite_where=sa.text(
                "is_primary = 1 AND deleted_at IS NULL AND document_status != 'SUPERSEDED'"
            ),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("student_documents", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_student_documents_primary",
            sqlite_where=sa.text(
                "is_primary = 1 AND deleted_at IS NULL AND document_status != 'SUPERSEDED'"
            ),
        )
        batch_op.drop_index("ix_student_documents_student_status")
        batch_op.drop_index(batch_op.f("ix_student_documents_student_id"))
        batch_op.drop_index(batch_op.f("ix_student_documents_file_object_id"))
        batch_op.drop_index(batch_op.f("ix_student_documents_category_id"))

    op.drop_table("student_documents")
    with op.batch_alter_table("student_document_requirements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_student_document_requirements_category_id"))

    op.drop_table("student_document_requirements")
    with op.batch_alter_table("file_replicas", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_file_replicas_primary",
            sqlite_where=sa.text("is_primary = 1 AND deleted_at IS NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_file_replicas_file_object_id"))

    op.drop_table("file_replicas")
    with op.batch_alter_table("document_category_allowed_types", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_category_allowed_types_category_id"))

    op.drop_table("document_category_allowed_types")
    with op.batch_alter_table("file_objects", schema=None) as batch_op:
        batch_op.drop_index("ix_file_objects_status")
        batch_op.drop_index(batch_op.f("ix_file_objects_sha256"))

    op.drop_table("file_objects")
    op.drop_table("document_categories")
    # ### end Alembic commands ###
