"""sprint4_exam_certificate

Revision ID: c8ddc70c572c
Revises: 0699df8f1196
Create Date: 2026-09-23 07:32:54.740012
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c8ddc70c572c"
down_revision: str | None = "0699df8f1196"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exam_batches",
        sa.Column("batch_code", sa.String(length=40), nullable=False),
        sa.Column("batch_name", sa.String(length=160), nullable=False),
        sa.Column("exam_scheme_version_id", sa.String(length=36), nullable=False),
        sa.Column("exam_start_date", sa.Date(), nullable=False),
        sa.Column("exam_end_date", sa.Date(), nullable=False),
        sa.Column("batch_status", sa.String(length=30), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exam_scheme_version_id"],
            ["exam_scheme_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_code"),
    )
    op.create_table(
        "certificate_cases",
        sa.Column("certificate_case_no", sa.String(length=40), nullable=False),
        sa.Column("course_enrollment_id", sa.String(length=36), nullable=False),
        sa.Column("eligibility_status", sa.String(length=30), nullable=False),
        sa.Column("certificate_status", sa.String(length=30), nullable=False),
        sa.Column("certificate_no_ciphertext", sa.Text(), nullable=True),
        sa.Column("certificate_no_last4", sa.String(length=4), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_enrollment_id"],
            ["course_enrollments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("certificate_case_no"),
        sa.UniqueConstraint("course_enrollment_id"),
    )
    op.create_table(
        "exam_attempts",
        sa.Column("course_enrollment_id", sa.String(length=36), nullable=False),
        sa.Column("course_subject_version_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("attempt_type", sa.String(length=20), nullable=False),
        sa.Column("score_value_scaled", sa.Integer(), nullable=True),
        sa.Column("score_scale", sa.Integer(), nullable=False),
        sa.Column("result_status", sa.String(length=20), nullable=False),
        sa.Column("result_confirm_status", sa.String(length=30), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_by", sa.String(length=36), nullable=True),
        sa.Column("current_revision_no", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["course_enrollment_id"],
            ["course_enrollments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["course_subject_version_id"],
            ["course_subject_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_enrollment_id", "course_subject_version_id", "attempt_no"),
    )
    with op.batch_alter_table("exam_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exam_attempts_course_enrollment_id"),
            ["course_enrollment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_exam_attempts_course_subject_version_id"),
            ["course_subject_version_id"],
            unique=False,
        )

    op.create_table(
        "exam_fee_assessments",
        sa.Column("assessment_no", sa.String(length=40), nullable=False),
        sa.Column("course_enrollment_id", sa.String(length=36), nullable=False),
        sa.Column("exam_attempt_id", sa.String(length=36), nullable=False),
        sa.Column("fee_type", sa.String(length=20), nullable=False),
        sa.Column("responsibility", sa.String(length=20), nullable=False),
        sa.Column("amount_cent", sa.Integer(), nullable=False),
        sa.Column("assessment_status", sa.String(length=30), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_enrollment_id"],
            ["course_enrollments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exam_attempt_id"],
            ["exam_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assessment_no"),
        sa.UniqueConstraint("exam_attempt_id", "fee_type"),
    )
    with op.batch_alter_table("exam_fee_assessments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exam_fee_assessments_course_enrollment_id"),
            ["course_enrollment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_exam_fee_assessments_exam_attempt_id"), ["exam_attempt_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exam_fee_assessments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_fee_assessments_exam_attempt_id"))
        batch_op.drop_index(batch_op.f("ix_exam_fee_assessments_course_enrollment_id"))

    op.drop_table("exam_fee_assessments")
    with op.batch_alter_table("exam_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_attempts_course_subject_version_id"))
        batch_op.drop_index(batch_op.f("ix_exam_attempts_course_enrollment_id"))

    op.drop_table("exam_attempts")
    op.drop_table("certificate_cases")
    op.drop_table("exam_batches")
    # ### end Alembic commands ###
