# ruff: noqa: E501, I001, UP007, UP035
"""add veteran funding allowance domain

Revision ID: d0d0739439c8
Revises: 12026a69e619
Create Date: 2026-09-23 11:48:38.581859
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "d0d0739439c8"
down_revision: Union[str, None] = "12026a69e619"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "funding_programs",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("program_code", sa.String(length=40), nullable=False),
        sa.Column("program_name", sa.String(length=120), nullable=False),
        sa.Column("department", sa.String(length=80), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "program_code"),
    )
    with op.batch_alter_table("funding_programs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_funding_programs_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "funding_sources",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("source_code", sa.String(length=40), nullable=False),
        sa.Column("source_name", sa.String(length=120), nullable=False),
        sa.Column("department", sa.String(length=80), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "source_code"),
    )
    with op.batch_alter_table("funding_sources", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_funding_sources_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "funding_program_versions",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("funding_program_id", sa.String(length=36), nullable=False),
        sa.Column("version_no", sa.String(length=30), nullable=False),
        sa.Column("region", sa.String(length=60), nullable=False),
        sa.Column("department", sa.String(length=80), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("policy_document_no", sa.String(length=80), nullable=True),
        sa.Column("policy_document_file_object_id", sa.String(length=36), nullable=True),
        sa.Column("program_status", sa.String(length=30), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_by", sa.String(length=36), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["funding_program_id"],
            ["funding_programs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_document_file_object_id"],
            ["file_objects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("funding_program_id", "version_no"),
    )
    with op.batch_alter_table("funding_program_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_funding_program_versions_funding_program_id"),
            ["funding_program_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_funding_program_versions_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_funding_program_versions_program_status"),
            ["program_status"],
            unique=False,
        )
        batch_op.create_index(
            "ix_funding_program_versions_scope",
            ["organization_id", "region", "department"],
            unique=False,
        )

    op.create_table(
        "veteran_identities",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("retirement_card_no_encrypted", sa.Text(), nullable=True),
        sa.Column("retirement_card_no_hmac", sa.String(length=128), nullable=True),
        sa.Column("retirement_card_no_masked", sa.String(length=60), nullable=True),
        sa.Column("retirement_card_no_key_version", sa.String(length=20), nullable=True),
        sa.Column("retired_on", sa.Date(), nullable=True),
        sa.Column("service_branch", sa.String(length=80), nullable=True),
        sa.Column("identity_status", sa.String(length=30), nullable=False),
        sa.Column("verified_status", sa.String(length=30), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "student_id"),
    )
    with op.batch_alter_table("veteran_identities", schema=None) as batch_op:
        batch_op.create_index(
            "ix_veteran_identities_hmac",
            ["organization_id", "retirement_card_no_hmac"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_veteran_identities_identity_status"), ["identity_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_veteran_identities_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_veteran_identities_student_id"), ["student_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_veteran_identities_verified_status"), ["verified_status"], unique=False
        )

    op.create_table(
        "allowance_policies",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("region", sa.String(length=60), nullable=False),
        sa.Column("department", sa.String(length=80), nullable=False),
        sa.Column("funding_program_version_id", sa.String(length=36), nullable=False),
        sa.Column("allowance_type", sa.String(length=30), nullable=False),
        sa.Column("version_no", sa.String(length=30), nullable=False),
        sa.Column("policy_document_no", sa.String(length=80), nullable=True),
        sa.Column("policy_document_file_object_id", sa.String(length=36), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("basis_rule", sa.String(length=30), nullable=False),
        sa.Column("unit_amount_cent", sa.Integer(), nullable=False),
        sa.Column("daily_cap_cent", sa.Integer(), nullable=True),
        sa.Column("total_cap_cent", sa.Integer(), nullable=True),
        sa.Column("half_day_threshold_minutes", sa.Integer(), nullable=True),
        sa.Column("full_day_threshold_minutes", sa.Integer(), nullable=True),
        sa.Column("rounding_rule", sa.String(length=20), nullable=False),
        sa.Column("rule_params_json", sa.Text(), nullable=True),
        sa.Column("policy_status", sa.String(length=30), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_by", sa.String(length=36), nullable=True),
        sa.Column("test_sample_json", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("unit_amount_cent >= 0", name="ck_allowance_policy_unit_nonneg"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["funding_program_version_id"],
            ["funding_program_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_document_file_object_id"],
            ["file_objects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "region",
            "department",
            "funding_program_version_id",
            "allowance_type",
            "version_no",
        ),
    )
    with op.batch_alter_table("allowance_policies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_allowance_policies_funding_program_version_id"),
            ["funding_program_version_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_allowance_policies_lookup",
            ["organization_id", "region", "department", "allowance_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_allowance_policies_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_allowance_policies_policy_status"), ["policy_status"], unique=False
        )

    op.create_table(
        "program_funding_sources",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("funding_program_version_id", sa.String(length=36), nullable=False),
        sa.Column("funding_source_id", sa.String(length=36), nullable=False),
        sa.Column("allocation_rule_type", sa.String(length=30), nullable=False),
        sa.Column("allocation_ratio_bp", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "allocation_ratio_bp IS NULL OR (allocation_ratio_bp >= 0 AND allocation_ratio_bp <= 10000)",
            name="ck_program_funding_source_ratio_range",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["funding_program_version_id"],
            ["funding_program_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["funding_source_id"],
            ["funding_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("funding_program_version_id", "funding_source_id"),
    )
    with op.batch_alter_table("program_funding_sources", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_program_funding_sources_funding_program_version_id"),
            ["funding_program_version_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_program_funding_sources_funding_source_id"),
            ["funding_source_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_program_funding_sources_organization_id"),
            ["organization_id"],
            unique=False,
        )

    op.create_table(
        "veteran_attribute_histories",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("veteran_identity_id", sa.String(length=36), nullable=False),
        sa.Column("attribute_code", sa.String(length=60), nullable=False),
        sa.Column("value_text", sa.String(length=200), nullable=True),
        sa.Column("value_date", sa.Date(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=120), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["veteran_identity_id"],
            ["veteran_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("veteran_attribute_histories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_veteran_attribute_histories_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_veteran_attribute_histories_veteran_identity_id"),
            ["veteran_identity_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_veteran_attribute_lookup", ["veteran_identity_id", "attribute_code"], unique=False
        )

    op.create_table(
        "veteran_identity_evidences",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("veteran_identity_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_type", sa.String(length=40), nullable=False),
        sa.Column("file_object_id", sa.String(length=36), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_object_id"],
            ["file_objects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["veteran_identity_id"],
            ["veteran_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("veteran_identity_id", "evidence_type", "file_object_id"),
    )
    with op.batch_alter_table("veteran_identity_evidences", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_veteran_identity_evidences_file_object_id"),
            ["file_object_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_veteran_identity_evidences_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_veteran_identity_evidences_veteran_identity_id"),
            ["veteran_identity_id"],
            unique=False,
        )

    op.create_table(
        "veteran_identity_verifications",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("veteran_identity_id", sa.String(length=36), nullable=False),
        sa.Column("verification_no", sa.String(length=40), nullable=False),
        sa.Column("verification_status", sa.String(length=30), nullable=False),
        sa.Column("method", sa.String(length=60), nullable=True),
        sa.Column("verified_on", sa.Date(), nullable=True),
        sa.Column("verified_by", sa.String(length=36), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["veteran_identity_id"],
            ["veteran_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "verification_no"),
    )
    with op.batch_alter_table("veteran_identity_verifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_veteran_identity_verifications_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_veteran_identity_verifications_verification_status"),
            ["verification_status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_veteran_identity_verifications_veteran_identity_id"),
            ["veteran_identity_id"],
            unique=False,
        )

    op.create_table(
        "attendance_day_facts",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("course_enrollment_id", sa.String(length=36), nullable=False),
        sa.Column("class_cycle_id", sa.String(length=36), nullable=True),
        sa.Column("fact_date", sa.Date(), nullable=False),
        sa.Column("source_session_ids_json", sa.Text(), nullable=True),
        sa.Column("planned_minutes", sa.Integer(), nullable=False),
        sa.Column("attended_minutes", sa.Integer(), nullable=False),
        sa.Column("late_minutes", sa.Integer(), nullable=False),
        sa.Column("early_leave_minutes", sa.Integer(), nullable=False),
        sa.Column("leave_minutes", sa.Integer(), nullable=False),
        sa.Column("absent_minutes", sa.Integer(), nullable=False),
        sa.Column("day_part", sa.String(length=20), nullable=False),
        sa.Column("fact_version", sa.Integer(), nullable=False),
        sa.Column("fact_status", sa.String(length=30), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("superseded_by_fact_id", sa.String(length=36), nullable=True),
        sa.Column("basis_json", sa.Text(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_by", sa.String(length=36), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("attended_minutes >= 0", name="ck_day_fact_attended_nonneg"),
        sa.CheckConstraint("planned_minutes >= 0", name="ck_day_fact_planned_nonneg"),
        sa.ForeignKeyConstraint(
            ["class_cycle_id"],
            ["class_cycles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["course_enrollment_id"],
            ["course_enrollments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_fact_id"],
            ["attendance_day_facts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attendance_day_facts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attendance_day_facts_course_enrollment_id"),
            ["course_enrollment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_attendance_day_facts_fact_date"), ["fact_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attendance_day_facts_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attendance_day_facts_student_id"), ["student_id"], unique=False
        )
        batch_op.create_index(
            "uq_attendance_day_fact_current",
            ["student_id", "course_enrollment_id", "fact_date"],
            unique=True,
            sqlite_where=sa.text("is_current = 1"),
        )

    op.create_table(
        "funding_cases",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("course_enrollment_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("funding_program_version_id", sa.String(length=36), nullable=False),
        sa.Column("region", sa.String(length=60), nullable=False),
        sa.Column("department", sa.String(length=80), nullable=False),
        sa.Column("case_status", sa.String(length=30), nullable=False),
        sa.Column("policy_snapshot_json", sa.Text(), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_enrollment_id"],
            ["course_enrollments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["funding_program_version_id"],
            ["funding_program_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_enrollment_id"),
    )
    with op.batch_alter_table("funding_cases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_funding_cases_case_status"), ["case_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_funding_cases_course_enrollment_id"),
            ["course_enrollment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_funding_cases_funding_program_version_id"),
            ["funding_program_version_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_funding_cases_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            "ix_funding_cases_status", ["organization_id", "case_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_funding_cases_student_id"), ["student_id"], unique=False
        )

    op.create_table(
        "lodging_stays",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("course_enrollment_id", sa.String(length=36), nullable=False),
        sa.Column("class_cycle_id", sa.String(length=36), nullable=True),
        sa.Column("check_in_date", sa.Date(), nullable=False),
        sa.Column("check_out_date", sa.Date(), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("is_school_arranged", sa.Boolean(), nullable=False),
        sa.Column("review_status", sa.String(length=30), nullable=False),
        sa.Column("evidence_file_object_id", sa.String(length=36), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.String(length=36), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("check_out_date >= check_in_date", name="ck_lodging_stay_date_order"),
        sa.ForeignKeyConstraint(
            ["class_cycle_id"],
            ["class_cycles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["course_enrollment_id"],
            ["course_enrollments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evidence_file_object_id"],
            ["file_objects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "idempotency_key"),
    )
    with op.batch_alter_table("lodging_stays", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lodging_stays_course_enrollment_id"),
            ["course_enrollment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lodging_stays_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lodging_stays_review_status"), ["review_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lodging_stays_student_id"), ["student_id"], unique=False
        )

    op.create_table(
        "project_costs",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("class_cycle_id", sa.String(length=36), nullable=False),
        sa.Column("funding_program_version_id", sa.String(length=36), nullable=True),
        sa.Column("cost_type", sa.String(length=40), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("amount_cent", sa.Integer(), nullable=False),
        sa.Column("cost_status", sa.String(length=30), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_by", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("amount_cent >= 0", name="ck_project_cost_amount_nonneg"),
        sa.ForeignKeyConstraint(
            ["class_cycle_id"],
            ["class_cycles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["funding_program_version_id"],
            ["funding_program_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "idempotency_key"),
    )
    with op.batch_alter_table("project_costs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_costs_class_cycle_id"), ["class_cycle_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_project_costs_cost_type"), ["cost_type"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_project_costs_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "allowance_payables",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("funding_case_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("allowance_type", sa.String(length=30), nullable=False),
        sa.Column("payable_amount_cent", sa.Integer(), nullable=False),
        sa.Column("paid_amount_cent", sa.Integer(), nullable=False),
        sa.Column("payable_status", sa.String(length=30), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("paid_amount_cent >= 0", name="ck_allowance_payable_paid_nonneg"),
        sa.CheckConstraint("payable_amount_cent >= 0", name="ck_allowance_payable_amount_nonneg"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["funding_case_id"],
            ["funding_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("funding_case_id", "allowance_type"),
    )
    with op.batch_alter_table("allowance_payables", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_allowance_payables_funding_case_id"), ["funding_case_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_allowance_payables_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_allowance_payables_payable_status"), ["payable_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_allowance_payables_student_id"), ["student_id"], unique=False
        )

    op.create_table(
        "eligibility_assessments",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("funding_case_id", sa.String(length=36), nullable=False),
        sa.Column("assessment_version", sa.Integer(), nullable=False),
        sa.Column("assessment_status", sa.String(length=30), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("basis_json", sa.Text(), nullable=True),
        sa.Column("assessed_on", sa.Date(), nullable=True),
        sa.Column("assessed_by", sa.String(length=36), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["funding_case_id"],
            ["funding_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("eligibility_assessments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_eligibility_assessments_assessment_status"),
            ["assessment_status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_eligibility_assessments_funding_case_id"),
            ["funding_case_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_eligibility_assessments_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            "uq_eligibility_assessment_current",
            ["funding_case_id"],
            unique=True,
            sqlite_where=sa.text("is_current = 1"),
        )

    op.create_table(
        "funding_case_components",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("funding_case_id", sa.String(length=36), nullable=False),
        sa.Column("component_type", sa.String(length=40), nullable=False),
        sa.Column("component_status", sa.String(length=30), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["funding_case_id"],
            ["funding_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("funding_case_id", "component_type"),
    )
    with op.batch_alter_table("funding_case_components", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_funding_case_components_funding_case_id"),
            ["funding_case_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_funding_case_components_organization_id"),
            ["organization_id"],
            unique=False,
        )

    op.create_table(
        "lodging_night_facts",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("lodging_stay_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("course_enrollment_id", sa.String(length=36), nullable=False),
        sa.Column("night_date", sa.Date(), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("is_school_arranged", sa.Boolean(), nullable=False),
        sa.Column("review_status", sa.String(length=30), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_enrollment_id"],
            ["course_enrollments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lodging_stay_id"],
            ["lodging_stays.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lodging_stay_id", "night_date"),
    )
    with op.batch_alter_table("lodging_night_facts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lodging_night_facts_course_enrollment_id"),
            ["course_enrollment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lodging_night_facts_lodging_stay_id"), ["lodging_stay_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lodging_night_facts_night_date"), ["night_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lodging_night_facts_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lodging_night_facts_student_id"), ["student_id"], unique=False
        )
        batch_op.create_index(
            "uq_lodging_night_fact_approved",
            ["student_id", "night_date"],
            unique=True,
            sqlite_where=sa.text("review_status = 'APPROVED'"),
        )

    op.create_table(
        "project_cost_allocations",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_cost_id", sa.String(length=36), nullable=False),
        sa.Column("allocation_basis", sa.String(length=30), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=True),
        sa.Column("course_enrollment_id", sa.String(length=36), nullable=True),
        sa.Column("amount_cent", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("amount_cent >= 0", name="ck_project_cost_alloc_amount_nonneg"),
        sa.ForeignKeyConstraint(
            ["course_enrollment_id"],
            ["course_enrollments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_cost_id"],
            ["project_costs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_cost_id", "course_enrollment_id"),
    )
    with op.batch_alter_table("project_cost_allocations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_cost_allocations_course_enrollment_id"),
            ["course_enrollment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_project_cost_allocations_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_project_cost_allocations_project_cost_id"),
            ["project_cost_id"],
            unique=False,
        )

    op.create_table(
        "subsidy_entitlements",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("funding_case_id", sa.String(length=36), nullable=False),
        sa.Column("course_enrollment_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("allowance_type", sa.String(length=30), nullable=False),
        sa.Column("region", sa.String(length=60), nullable=False),
        sa.Column("department", sa.String(length=80), nullable=False),
        sa.Column("allowance_policy_id", sa.String(length=36), nullable=False),
        sa.Column("entitlement_version", sa.Integer(), nullable=False),
        sa.Column("computed_amount_cent", sa.Integer(), nullable=False),
        sa.Column("adjusted_amount_cent", sa.Integer(), nullable=False),
        sa.Column("entitlement_status", sa.String(length=30), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("covered_day_count", sa.Integer(), nullable=False),
        sa.Column("covered_night_count", sa.Integer(), nullable=False),
        sa.Column("basis_json", sa.Text(), nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("computed_by", sa.String(length=36), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "computed_amount_cent >= 0", name="ck_subsidy_entitlement_amount_nonneg"
        ),
        sa.ForeignKeyConstraint(
            ["allowance_policy_id"],
            ["allowance_policies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["computed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["course_enrollment_id"],
            ["course_enrollments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["funding_case_id"],
            ["funding_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("subsidy_entitlements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subsidy_entitlements_allowance_policy_id"),
            ["allowance_policy_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_subsidy_entitlements_course_enrollment_id"),
            ["course_enrollment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_subsidy_entitlements_entitlement_status"),
            ["entitlement_status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_subsidy_entitlements_funding_case_id"), ["funding_case_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_subsidy_entitlements_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_subsidy_entitlements_student_id"), ["student_id"], unique=False
        )
        batch_op.create_index(
            "uq_subsidy_entitlement_current",
            ["funding_case_id", "allowance_type", "allowance_policy_id"],
            unique=True,
            sqlite_where=sa.text("is_current = 1"),
        )

    op.create_table(
        "allowance_payments",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("allowance_payable_id", sa.String(length=36), nullable=False),
        sa.Column("amount_cent", sa.Integer(), nullable=False),
        sa.Column("payment_method", sa.String(length=40), nullable=False),
        sa.Column("payment_status", sa.String(length=30), nullable=False),
        sa.Column("paid_on", sa.Date(), nullable=True),
        sa.Column("reversed_by_payment_id", sa.String(length=36), nullable=True),
        sa.Column("failure_code", sa.String(length=40), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("amount_cent > 0", name="ck_allowance_payment_amount_positive"),
        sa.ForeignKeyConstraint(
            ["allowance_payable_id"],
            ["allowance_payables.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reversed_by_payment_id"],
            ["allowance_payments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "idempotency_key"),
    )
    with op.batch_alter_table("allowance_payments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_allowance_payments_allowance_payable_id"),
            ["allowance_payable_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_allowance_payments_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_allowance_payments_payment_status"), ["payment_status"], unique=False
        )

    op.create_table(
        "eligibility_evidences",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("eligibility_assessment_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_type", sa.String(length=40), nullable=False),
        sa.Column("file_object_id", sa.String(length=36), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["eligibility_assessment_id"],
            ["eligibility_assessments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_object_id"],
            ["file_objects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("eligibility_assessment_id", "evidence_type", "file_object_id"),
    )
    with op.batch_alter_table("eligibility_evidences", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_eligibility_evidences_eligibility_assessment_id"),
            ["eligibility_assessment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_eligibility_evidences_file_object_id"), ["file_object_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_eligibility_evidences_organization_id"),
            ["organization_id"],
            unique=False,
        )

    op.create_table(
        "entitlement_adjustments",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("subsidy_entitlement_id", sa.String(length=36), nullable=False),
        sa.Column("adjustment_type", sa.String(length=30), nullable=False),
        sa.Column("amount_delta_cent", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("adjustment_of_id", sa.String(length=36), nullable=True),
        sa.Column("accounting_date", sa.Date(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("amount_delta_cent <> 0", name="ck_entitlement_adjustment_nonzero"),
        sa.ForeignKeyConstraint(
            ["adjustment_of_id"],
            ["entitlement_adjustments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subsidy_entitlement_id"],
            ["subsidy_entitlements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "idempotency_key"),
    )
    with op.batch_alter_table("entitlement_adjustments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entitlement_adjustments_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_entitlement_adjustments_subsidy_entitlement_id"),
            ["subsidy_entitlement_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entitlement_adjustments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entitlement_adjustments_subsidy_entitlement_id"))
        batch_op.drop_index(batch_op.f("ix_entitlement_adjustments_organization_id"))

    op.drop_table("entitlement_adjustments")
    with op.batch_alter_table("eligibility_evidences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eligibility_evidences_organization_id"))
        batch_op.drop_index(batch_op.f("ix_eligibility_evidences_file_object_id"))
        batch_op.drop_index(batch_op.f("ix_eligibility_evidences_eligibility_assessment_id"))

    op.drop_table("eligibility_evidences")
    with op.batch_alter_table("allowance_payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_allowance_payments_payment_status"))
        batch_op.drop_index(batch_op.f("ix_allowance_payments_organization_id"))
        batch_op.drop_index(batch_op.f("ix_allowance_payments_allowance_payable_id"))

    op.drop_table("allowance_payments")
    with op.batch_alter_table("subsidy_entitlements", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_subsidy_entitlement_current", sqlite_where=sa.text("is_current = 1")
        )
        batch_op.drop_index(batch_op.f("ix_subsidy_entitlements_student_id"))
        batch_op.drop_index(batch_op.f("ix_subsidy_entitlements_organization_id"))
        batch_op.drop_index(batch_op.f("ix_subsidy_entitlements_funding_case_id"))
        batch_op.drop_index(batch_op.f("ix_subsidy_entitlements_entitlement_status"))
        batch_op.drop_index(batch_op.f("ix_subsidy_entitlements_course_enrollment_id"))
        batch_op.drop_index(batch_op.f("ix_subsidy_entitlements_allowance_policy_id"))

    op.drop_table("subsidy_entitlements")
    with op.batch_alter_table("project_cost_allocations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_cost_allocations_project_cost_id"))
        batch_op.drop_index(batch_op.f("ix_project_cost_allocations_organization_id"))
        batch_op.drop_index(batch_op.f("ix_project_cost_allocations_course_enrollment_id"))

    op.drop_table("project_cost_allocations")
    with op.batch_alter_table("lodging_night_facts", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_lodging_night_fact_approved", sqlite_where=sa.text("review_status = 'APPROVED'")
        )
        batch_op.drop_index(batch_op.f("ix_lodging_night_facts_student_id"))
        batch_op.drop_index(batch_op.f("ix_lodging_night_facts_organization_id"))
        batch_op.drop_index(batch_op.f("ix_lodging_night_facts_night_date"))
        batch_op.drop_index(batch_op.f("ix_lodging_night_facts_lodging_stay_id"))
        batch_op.drop_index(batch_op.f("ix_lodging_night_facts_course_enrollment_id"))

    op.drop_table("lodging_night_facts")
    with op.batch_alter_table("funding_case_components", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_funding_case_components_organization_id"))
        batch_op.drop_index(batch_op.f("ix_funding_case_components_funding_case_id"))

    op.drop_table("funding_case_components")
    with op.batch_alter_table("eligibility_assessments", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_eligibility_assessment_current", sqlite_where=sa.text("is_current = 1")
        )
        batch_op.drop_index(batch_op.f("ix_eligibility_assessments_organization_id"))
        batch_op.drop_index(batch_op.f("ix_eligibility_assessments_funding_case_id"))
        batch_op.drop_index(batch_op.f("ix_eligibility_assessments_assessment_status"))

    op.drop_table("eligibility_assessments")
    with op.batch_alter_table("allowance_payables", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_allowance_payables_student_id"))
        batch_op.drop_index(batch_op.f("ix_allowance_payables_payable_status"))
        batch_op.drop_index(batch_op.f("ix_allowance_payables_organization_id"))
        batch_op.drop_index(batch_op.f("ix_allowance_payables_funding_case_id"))

    op.drop_table("allowance_payables")
    with op.batch_alter_table("project_costs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_costs_organization_id"))
        batch_op.drop_index(batch_op.f("ix_project_costs_cost_type"))
        batch_op.drop_index(batch_op.f("ix_project_costs_class_cycle_id"))

    op.drop_table("project_costs")
    with op.batch_alter_table("lodging_stays", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lodging_stays_student_id"))
        batch_op.drop_index(batch_op.f("ix_lodging_stays_review_status"))
        batch_op.drop_index(batch_op.f("ix_lodging_stays_organization_id"))
        batch_op.drop_index(batch_op.f("ix_lodging_stays_course_enrollment_id"))

    op.drop_table("lodging_stays")
    with op.batch_alter_table("funding_cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_funding_cases_student_id"))
        batch_op.drop_index("ix_funding_cases_status")
        batch_op.drop_index(batch_op.f("ix_funding_cases_organization_id"))
        batch_op.drop_index(batch_op.f("ix_funding_cases_funding_program_version_id"))
        batch_op.drop_index(batch_op.f("ix_funding_cases_course_enrollment_id"))
        batch_op.drop_index(batch_op.f("ix_funding_cases_case_status"))

    op.drop_table("funding_cases")
    with op.batch_alter_table("attendance_day_facts", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_attendance_day_fact_current", sqlite_where=sa.text("is_current = 1")
        )
        batch_op.drop_index(batch_op.f("ix_attendance_day_facts_student_id"))
        batch_op.drop_index(batch_op.f("ix_attendance_day_facts_organization_id"))
        batch_op.drop_index(batch_op.f("ix_attendance_day_facts_fact_date"))
        batch_op.drop_index(batch_op.f("ix_attendance_day_facts_course_enrollment_id"))

    op.drop_table("attendance_day_facts")
    with op.batch_alter_table("veteran_identity_verifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_veteran_identity_verifications_veteran_identity_id"))
        batch_op.drop_index(batch_op.f("ix_veteran_identity_verifications_verification_status"))
        batch_op.drop_index(batch_op.f("ix_veteran_identity_verifications_organization_id"))

    op.drop_table("veteran_identity_verifications")
    with op.batch_alter_table("veteran_identity_evidences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_veteran_identity_evidences_veteran_identity_id"))
        batch_op.drop_index(batch_op.f("ix_veteran_identity_evidences_organization_id"))
        batch_op.drop_index(batch_op.f("ix_veteran_identity_evidences_file_object_id"))

    op.drop_table("veteran_identity_evidences")
    with op.batch_alter_table("veteran_attribute_histories", schema=None) as batch_op:
        batch_op.drop_index("ix_veteran_attribute_lookup")
        batch_op.drop_index(batch_op.f("ix_veteran_attribute_histories_veteran_identity_id"))
        batch_op.drop_index(batch_op.f("ix_veteran_attribute_histories_organization_id"))

    op.drop_table("veteran_attribute_histories")
    with op.batch_alter_table("program_funding_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_program_funding_sources_organization_id"))
        batch_op.drop_index(batch_op.f("ix_program_funding_sources_funding_source_id"))
        batch_op.drop_index(batch_op.f("ix_program_funding_sources_funding_program_version_id"))

    op.drop_table("program_funding_sources")
    with op.batch_alter_table("allowance_policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_allowance_policies_policy_status"))
        batch_op.drop_index(batch_op.f("ix_allowance_policies_organization_id"))
        batch_op.drop_index("ix_allowance_policies_lookup")
        batch_op.drop_index(batch_op.f("ix_allowance_policies_funding_program_version_id"))

    op.drop_table("allowance_policies")
    with op.batch_alter_table("veteran_identities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_veteran_identities_verified_status"))
        batch_op.drop_index(batch_op.f("ix_veteran_identities_student_id"))
        batch_op.drop_index(batch_op.f("ix_veteran_identities_organization_id"))
        batch_op.drop_index(batch_op.f("ix_veteran_identities_identity_status"))
        batch_op.drop_index("ix_veteran_identities_hmac")

    op.drop_table("veteran_identities")
    with op.batch_alter_table("funding_program_versions", schema=None) as batch_op:
        batch_op.drop_index("ix_funding_program_versions_scope")
        batch_op.drop_index(batch_op.f("ix_funding_program_versions_program_status"))
        batch_op.drop_index(batch_op.f("ix_funding_program_versions_organization_id"))
        batch_op.drop_index(batch_op.f("ix_funding_program_versions_funding_program_id"))

    op.drop_table("funding_program_versions")
    with op.batch_alter_table("funding_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_funding_sources_organization_id"))

    op.drop_table("funding_sources")
    with op.batch_alter_table("funding_programs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_funding_programs_organization_id"))

    op.drop_table("funding_programs")
    # ### end Alembic commands ###
