<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { useRouter } from 'vue-router'
import { api } from '../api'
type Cycle = { id:string; class_code:string; class_name:string; course_name:string; version_name:string; active_member_count:number; capacity:number | null; class_status:string }
const rows = ref<Cycle[]>([]); const members = ref<Record<string, unknown>[]>([]); const selected = ref<Cycle | null>(null); const router = useRouter()
const courses = ref<{ id:string; course_name:string }[]>([]); const versions = ref<{ id:string; version_name:string; status:string }[]>([]); const enrollments = ref<{ id:string; enrollment_no:string; course_name:string; lifecycle_status:string }[]>([]); const form = ref({ class_code:'', class_name:'', course_id:'', course_offering_version_id:'', capacity: undefined as number | undefined }); const memberEnrollmentId = ref('')
async function load() { rows.value = (await api<{items:Cycle[]}>('/classes')).items; courses.value = (await api<{items:{id:string;course_name:string}[]}>('/courses')).items; enrollments.value = (await api<{items:{id:string;enrollment_no:string;course_name:string;lifecycle_status:string}[]}>('/enrollments')).items }
async function courseChanged() { versions.value = form.value.course_id ? (await api<{items:{id:string;version_name:string;status:string}[]}>(`/courses/${form.value.course_id}/versions`)).items.filter(item=>item.status==='PUBLISHED') : []; form.value.course_offering_version_id = '' }
async function create() { try { await api('/classes', { method:'POST', body:JSON.stringify({ class_code:form.value.class_code, class_name:form.value.class_name, course_offering_version_id:form.value.course_offering_version_id, capacity:form.value.capacity, class_status:'OPEN' }) }); await load(); ElMessage.success('班级已创建') } catch (error) { ElMessage.error(error instanceof Error ? error.message : '创建失败') } }
async function addMember() { if (!selected.value || !memberEnrollmentId.value) return; try { await api(`/classes/${selected.value.id}/members`, { method:'POST', body:JSON.stringify({ course_enrollment_id:memberEnrollmentId.value, idempotency_key:crypto.randomUUID() }) }); await select(selected.value); ElMessage.success('成员已加入班级') } catch (error) { ElMessage.error(error instanceof Error ? error.message : '加入失败') } }
async function select(cycle:Cycle) { selected.value = cycle; members.value = (await api<{items:Record<string, unknown>[]}>(`/classes/${cycle.id}/members`)).items }
function student(row:Record<string, unknown>) { router.push({ name:'student-detail', params:{ id:String(row.student_id) }, query:{ returnTo:`/classes?classId=${selected.value?.id}`, tab:'classes' } }) }
onMounted(load)
</script>
<template><section><h1>班级</h1><p>班级成员通过报名关联，不能把其他课程版本的报名加入本班。</p><el-card><el-form inline @submit.prevent="create"><el-form-item label="班级编码"><el-input v-model="form.class_code"/></el-form-item><el-form-item label="班级名称"><el-input v-model="form.class_name"/></el-form-item><el-form-item label="课程"><el-select v-model="form.course_id" @change="courseChanged"><el-option v-for="course in courses" :key="course.id" :value="course.id" :label="course.course_name"/></el-select></el-form-item><el-form-item label="版本"><el-select v-model="form.course_offering_version_id"><el-option v-for="version in versions" :key="version.id" :value="version.id" :label="version.version_name"/></el-select></el-form-item><el-form-item label="容量"><el-input-number v-model="form.capacity" :min="1"/></el-form-item><el-button type="primary" :disabled="!form.class_code || !form.class_name || !form.course_offering_version_id" native-type="submit">创建班级</el-button></el-form></el-card><el-table :data="rows" @row-click="select" style="margin-top:16px"><el-table-column prop="class_code" label="班级编码"/><el-table-column prop="class_name" label="班级"/><el-table-column prop="course_name" label="课程"/><el-table-column prop="version_name" label="版本"/><el-table-column label="人数"><template #default="scope">{{ scope.row.active_member_count }}/{{ scope.row.capacity ?? '不限' }}</template></el-table-column><el-table-column prop="class_status" label="状态"/></el-table><el-card v-if="selected" style="margin-top:16px"><h2>{{ selected.class_name }} · 学员名单</h2><el-select v-model="memberEnrollmentId" filterable placeholder="选择报名后加入"><el-option v-for="enrollment in enrollments.filter(item => item.lifecycle_status === 'ACTIVE')" :key="enrollment.id" :value="enrollment.id" :label="`${enrollment.enrollment_no} · ${enrollment.course_name}`"/></el-select><el-button type="primary" @click="addMember">加入班级</el-button><el-table :data="members" @row-click="student" style="margin-top:12px"><el-table-column prop="student_no" label="学员编号"/><el-table-column prop="full_name" label="姓名"/><el-table-column prop="phone_masked" label="手机号"/><el-table-column prop="enrollment_no" label="报名编号"/><el-table-column prop="membership_status" label="成员状态"/></el-table></el-card></section></template>
