<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { api } from '../api'

type Course = { id: string; course_code: string; course_name: string; enabled: boolean }
const courses = ref<Course[]>([]); const selected = ref<Course | null>(null); const versions = ref<Record<string, unknown>[]>([])
const form = ref({ course_code: '', course_name: '' })
const versionForm = ref({ version_no: '', version_name: '', total_minutes: 240, tuition_amount_cent: 0 })
async function load() { courses.value = (await api<{ items: Course[] }>('/courses')).items }
async function select(course: Course) { selected.value = course; versions.value = (await api<{ items: Record<string, unknown>[] }>(`/courses/${course.id}/versions`)).items }
async function create() { try { await api('/courses', { method: 'POST', body: JSON.stringify(form.value) }); form.value = { course_code: '', course_name: '' }; await load(); ElMessage.success('课程已创建') } catch (error) { ElMessage.error(error instanceof Error ? error.message : '创建失败') } }
async function createVersion() { if (!selected.value) return; try { await api(`/courses/${selected.value.id}/versions`, { method:'POST', body:JSON.stringify({ version_no:versionForm.value.version_no, version_name:versionForm.value.version_name, curriculum:{ version_no:`${selected.value.course_code}-${versionForm.value.version_no}-CUR`, name:'课程方案', total_minutes:versionForm.value.total_minutes }, exam_scheme:{ version_no:`${selected.value.course_code}-${versionForm.value.version_no}-EXAM`, name:'考试方案', subjects:[{ subject_code:'S1', subject_name:'科目一' }] }, fee_policy:{ version_no:`${selected.value.course_code}-${versionForm.value.version_no}-FEE`, name:'收费规则', tuition_amount_cent:versionForm.value.tuition_amount_cent }, refund_policy:{ version_no:`${selected.value.course_code}-${versionForm.value.version_no}-REF`, name:'退费规则' } }) }); await select(selected.value); ElMessage.success('草稿版本已创建') } catch (error) { ElMessage.error(error instanceof Error ? error.message : '创建失败') } }
async function publish(version: Record<string, unknown>) { try { await api(`/course-versions/${version.id}/publish`, { method:'POST' }); if (selected.value) await select(selected.value); ElMessage.success('课程版本已发布') } catch (error) { ElMessage.error(error instanceof Error ? error.message : '发布失败') } }
onMounted(load)
</script>
<template><section><h1>课程管理</h1><p>课程目录存于数据库；已发布版本由后端锁定关键字段。</p><el-card><el-form inline @submit.prevent="create"><el-form-item label="课程编码"><el-input v-model="form.course_code"/></el-form-item><el-form-item label="课程名称"><el-input v-model="form.course_name"/></el-form-item><el-button type="primary" native-type="submit">新建课程</el-button></el-form></el-card><el-table :data="courses" @row-click="select"><el-table-column prop="course_code" label="编码"/><el-table-column prop="course_name" label="课程"/><el-table-column prop="enabled" label="启用"/></el-table><el-card v-if="selected" style="margin-top:16px"><h2>{{ selected.course_name }} 的版本</h2><el-form inline @submit.prevent="createVersion"><el-form-item label="版本号"><el-input v-model="versionForm.version_no"/></el-form-item><el-form-item label="版本名称"><el-input v-model="versionForm.version_name"/></el-form-item><el-form-item label="总分钟"><el-input-number v-model="versionForm.total_minutes" :min="1"/></el-form-item><el-form-item label="培训费（分）"><el-input-number v-model="versionForm.tuition_amount_cent" :min="0"/></el-form-item><el-button type="primary" :disabled="!versionForm.version_no || !versionForm.version_name" native-type="submit">创建草稿版本</el-button></el-form><el-table :data="versions"><el-table-column prop="version_no" label="版本"/><el-table-column prop="version_name" label="名称"/><el-table-column prop="status" label="状态"/><el-table-column prop="enrollment_count" label="报名数"/><el-table-column label="操作"><template #default="scope"><el-button v-if="scope.row.status === 'DRAFT'" type="primary" text @click="publish(scope.row)">发布</el-button><span v-else>只读</span></template></el-table-column></el-table></el-card></section></template>
