<script setup lang="ts">
import { reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { api } from '../api'
const file = ref<File | null>(null); const batch = ref<Record<string, unknown> | null>(null); const loading = ref(false); const actions = reactive<Record<string, { action:string; reason:string; student_id:string }>>({})
function choose(upload: { raw?: File }) { file.value = upload.raw ?? null }
async function download() { const response = await fetch('/api/imports/students/template', { credentials:'same-origin' }); const blob = await response.blob(); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'student-import-template.xlsx'; link.click(); URL.revokeObjectURL(link.href) }
async function preview() { if (!file.value) return; loading.value = true; try { const data = new FormData(); data.append('file', file.value); const response = await fetch('/api/imports/students/preview', { method:'POST', body:data, credentials:'same-origin', headers:{ 'X-CSRF-Token': document.cookie.split('; ').find(v=>v.startsWith('csrf_token='))?.split('=')[1] ?? '' } }); if (!response.ok) throw new Error((await response.json()).detail?.message ?? '预检失败'); batch.value = await response.json() } catch (error) { ElMessage.error(error instanceof Error ? error.message : '预检失败') } finally { loading.value = false } }
function actionFor(row: { row_number:number }) { return actions[String(row.row_number)] ?? (actions[String(row.row_number)] = { action:'skip', reason:'', student_id:'' }) }
async function confirm() { if (!batch.value) return; loading.value = true; try { batch.value = await api(`/imports/students/${String(batch.value.id)}/confirm`, { method:'POST', body:JSON.stringify({ idempotency_key:crypto.randomUUID(), possible_duplicate_actions:actions }) }); ElMessage.success('导入确认完成') } catch (error) { ElMessage.error(error instanceof Error ? error.message : '确认失败') } finally { loading.value = false } }
</script>
<template><section><h1>学员 Excel 导入</h1><p>先预检，不写入学员主档；确认后仅导入有效学员行。课程、报名和班级列会提示但本阶段不执行。</p><el-button @click="download">下载模板</el-button><el-upload :auto-upload="false" :limit="1" accept=".xlsx" @change="choose"><el-button>选择 Excel</el-button></el-upload><el-button type="primary" :loading="loading" :disabled="!file" @click="preview">开始预检</el-button><el-button v-if="batch?.status === 'PREVIEWED'" :loading="loading" @click="confirm">确认有效行</el-button><el-table v-if="batch" :data="Array.isArray(batch.items) ? batch.items : []" style="margin-top:16px"><el-table-column prop="row_number" label="行"/><el-table-column prop="status" label="状态"/><el-table-column label="结果"><template #default="scope">{{ scope.row.result?.message }}<template v-if="scope.row.status === 'POSSIBLE_DUPLICATE'"><el-select v-model="actionFor(scope.row).action" style="width:150px"><el-option label="跳过" value="skip"/><el-option label="关联已有学员" value="link"/><el-option label="仍然新建" value="create"/></el-select><el-select v-if="actionFor(scope.row).action === 'link'" v-model="actionFor(scope.row).student_id" placeholder="选择疑似学员"><el-option v-for="candidate in scope.row.result?.candidates ?? []" :key="candidate.student_id" :label="`${candidate.student_no} · ${candidate.full_name}`" :value="candidate.student_id"/></el-select><el-input v-if="actionFor(scope.row).action === 'create'" v-model="actionFor(scope.row).reason" placeholder="强制新建理由"/></template></template></el-table-column></el-table></section></template>
