<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { api } from '../api'
type Row = Record<string, any>
const batches = ref<Row[]>([]); const preview = ref<Row>({items:[]}); const start = ref(''); const end = ref(''); const selected = ref<Row|null>(null)
const yuan = (cent: unknown) => `¥${(Number(cent || 0)/100).toFixed(2)}`
async function load(){ batches.value=(await api<{items:Row[]}>('/teacher-settlement-batches')).items }
async function previewPeriod(){ if(!start.value||!end.value)return; preview.value=await api('/teacher-settlement-batches/preview',{method:'POST',body:JSON.stringify({period_start:start.value,period_end:end.value})}) }
async function createBatch(){ const batch=await api<Row>('/teacher-settlement-batches',{method:'POST',body:JSON.stringify({period_start:start.value,period_end:end.value})}); await api(`/teacher-settlement-batches/${batch.id}/calculate`,{method:'POST',body:JSON.stringify({version:batch.version})}); ElMessage.success('结算批次已计算'); await load() }
function choose(row:Row){selected.value=row}
onMounted(load)
</script>
<template><section class="page"><header><div><h1>教师结算工作台</h1><p>仅纳入已完成课次和已确认教师可结算分钟，金额使用课次费率快照按整数分计算。</p></div><el-button @click="$router.push('/')">返回工作台</el-button></header><el-card class="toolbar"><el-date-picker v-model="start" value-format="YYYY-MM-DD" placeholder="开始日期"/><el-date-picker v-model="end" value-format="YYYY-MM-DD" placeholder="结束日期"/><el-button @click="previewPeriod">预览</el-button><el-button type="primary" :disabled="!start||!end" @click="createBatch">生成并计算批次</el-button></el-card><el-table :data="preview.items"><el-table-column prop="service_date" label="服务日期"/><el-table-column prop="teacher_id" label="教师"/><el-table-column prop="class_session_id" label="课次"/><el-table-column prop="settleable_minutes" label="教师分钟"/><el-table-column label="金额"><template #default="s">{{yuan(s.row.amount_cent)}}</template></el-table-column></el-table><h2>结算批次</h2><el-table :data="batches" @row-click="choose"><el-table-column prop="batch_no" label="批次"/><el-table-column prop="period_start" label="开始"/><el-table-column prop="period_end" label="结束"/><el-table-column prop="total_minutes" label="分钟"/><el-table-column label="总额"><template #default="s">{{yuan(s.row.total_amount_cent)}}</template></el-table-column><el-table-column label="已付"><template #default="s">{{yuan(s.row.paid_amount_cent)}}</template></el-table-column><el-table-column prop="settlement_status" label="状态"/></el-table><el-drawer v-model="selected" title="课次结算明细" size="70%"><el-table :data="selected?.lines||[]"><el-table-column prop="service_date" label="日期"/><el-table-column prop="teacher_id" label="教师"/><el-table-column prop="class_session_id" label="课次"/><el-table-column prop="teaching_role" label="角色"/><el-table-column prop="settleable_minutes" label="教师分钟"/><el-table-column prop="rate_amount_cent" label="费率（分）"/><el-table-column prop="rate_unit_minutes" label="费率分钟"/><el-table-column label="结算额"><template #default="s">{{yuan(s.row.final_amount_cent)}}</template></el-table-column><el-table-column label="已付"><template #default="s">{{yuan(s.row.paid_amount_cent)}}</template></el-table-column></el-table></el-drawer></section></template>
<style scoped>.page{padding:24px}header{display:flex;justify-content:space-between}p{color:#667085}.toolbar{margin:18px 0}.toolbar :deep(.el-card__body){display:flex;gap:12px}h2{margin-top:28px}</style>
